library(usethis)
library(testthat)

#vector of numbers
v1 = c(1)
v2 = c(1,4)
v3 = c(2,6,1)
v4 = c(3,5,1,3)
v5 = c(1,4,4,2,9)
v6 = c(8,8,8,8,8,8)
v7 = c(1,1,4,4,3,2,1)
v8 = c(1,1,4,4,3,2,1,7)

#zeros
z1 = 0
z2 = c(0,0)
z6 = c(0,0,0,0,0,0)

#NAs
na1 = NA
na2 = c(NA,NA)
na6 = c(NA,NA,NA,NA,NA,NA)

#numbers and NAs
m2 = c(2, NA)
m3 = c(2, NA, 4)
m4 = c(2, NA, 3, 4)
m5 = c(2, 6, NA, NA, 1)

test_that("Summary Score functions works with length 1 vector", {
  expect_equal(             meanScore(x = v1), 1)
  expect_equal(      trimmedMeanScore(x = v1), 1)
  expect_equal(     weightedMeanScore(x = v1), 1)
  expect_equal(           medianScore(x = v1), 1)
  expect_equal(             modeScore(x = v1), 1)
  expect_equal(         midrangeScore(x = v1), 1)
  expect_equal(         midhingeScore(x = v1), 1)
  expect_equal(          trimeanScore(x = v1), 1)
  expect_equal(          briskowScore(x = v1), 0)
  expect_equal(  reviewedBriskowScore(x = v1), 0)
  expect_equal(interquartileMeanScore(x = v1), getDefaultNaValue())
  expect_equal(      weightedSumScore(x = v1), 1)
  expect_equal(           ssGseaScore(x = v1), getDefaultNaValue())
  expect_equal(             gsvaScore(x = v1), getDefaultNaValue())
  expect_equal(            plageScore(x = v1), getDefaultNaValue())
  expect_equal(                zScore(x = v1), getDefaultNaValue())

})

test_that("Summary Score functions works with length 2 vector", {
  expect_equal(             meanScore(x = v2), 2.5)
  expect_equal(      trimmedMeanScore(x = v2), 2.5)
  expect_equal(     weightedMeanScore(x = v2), 2.5)
  expect_equal(           medianScore(x = v2), 2.5)
  expect_equal(             modeScore(x = v2), 1)
  expect_equal(         midrangeScore(x = v2), 2.5)
  expect_equal(         midhingeScore(x = v2), 2.5)
  expect_equal(          trimeanScore(x = v2), 2.5)
  expect_equal(          briskowScore(x = v2), 0)
  expect_equal(  reviewedBriskowScore(x = v2), 0)
  expect_equal(interquartileMeanScore(x = v2), getDefaultNaValue())
  expect_equal(      weightedSumScore(x = v2), 5)
  expect_equal(           ssGseaScore(x = v2), getDefaultNaValue())
  expect_equal(             gsvaScore(x = v2), getDefaultNaValue())
  expect_equal(            plageScore(x = v2), getDefaultNaValue())
  expect_equal(                zScore(x = v2), getDefaultNaValue())
})

test_that("Summary Score functions works with length 3 vector", {
  expect_equal(             meanScore(x = v3), 3)
  expect_equal(      trimmedMeanScore(x = v3), 3)
  expect_equal(     weightedMeanScore(x = v3), 3)
  expect_equal(           medianScore(x = v3), 2)
  expect_equal(             modeScore(x = v3), 1)
  expect_equal(         midrangeScore(x = v3), 3.5)
  expect_equal(         midhingeScore(x = v3), 2.75)
  expect_equal(          trimeanScore(x = v3), 2.375)
  expect_equal(          briskowScore(x = v3), 0)
  expect_equal(  reviewedBriskowScore(x = v3), 0)
  expect_equal(interquartileMeanScore(x = v3), getDefaultNaValue())
  expect_equal(      weightedSumScore(x = v3), 9)
  expect_equal(           ssGseaScore(x = v3), getDefaultNaValue())
  expect_equal(             gsvaScore(x = v3), getDefaultNaValue())
  expect_equal(            plageScore(x = v3), getDefaultNaValue())
  expect_equal(                zScore(x = v3), getDefaultNaValue())
})

test_that("Summary Score functions works with length 4 vector", {
  expect_equal(             meanScore(x = v4), 3)
  expect_equal(      trimmedMeanScore(x = v4), 3)
  expect_equal(     weightedMeanScore(x = v4), 3)
  expect_equal(           medianScore(x = v4), 3)
  expect_equal(             modeScore(x = v4), 3)
  expect_equal(         midrangeScore(x = v4), 3)
  expect_equal(         midhingeScore(x = v4), 3)
  expect_equal(          trimeanScore(x = v4), 3)
  expect_equal(          briskowScore(x = v4), 0)
  expect_equal(  reviewedBriskowScore(x = v4), 0)
  expect_equal(interquartileMeanScore(x = v4), 3)
  expect_equal(      weightedSumScore(x = v4), 12)
  expect_equal(           ssGseaScore(x = v4), getDefaultNaValue())
  expect_equal(             gsvaScore(x = v4), getDefaultNaValue())
  expect_equal(            plageScore(x = v4), getDefaultNaValue())
  expect_equal(                zScore(x = v4), getDefaultNaValue())
})

test_that("Summary Score functions works with length 5 vector", {
  expect_equal(             meanScore(x = v5), 4)
  expect_equal(      trimmedMeanScore(x = v5), 4)
  expect_equal(     weightedMeanScore(x = v5), 4)
  expect_equal(           medianScore(x = v5), 4)
  expect_equal(             modeScore(x = v5), 4)
  expect_equal(         midrangeScore(x = v5), 5)
  expect_equal(         midhingeScore(x = v5), 3)
  expect_equal(          trimeanScore(x = v5), 3.5)
  expect_equal(          briskowScore(x = v5), -1)
  expect_equal(  reviewedBriskowScore(x = v5), -0.2)
  expect_equal(interquartileMeanScore(x = v5), 3.4)
  expect_equal(      weightedSumScore(x = v5), 20)
  expect_equal(           ssGseaScore(x = v5), getDefaultNaValue())
  expect_equal(             gsvaScore(x = v5), getDefaultNaValue())
  expect_equal(            plageScore(x = v5), getDefaultNaValue())
  expect_equal(                zScore(x = v5), getDefaultNaValue())
})


test_that("Summary Score functions works with length 6 vector of equal elements", {
  expect_equal(             meanScore(x = v6), 8)
  expect_equal(      trimmedMeanScore(x = v6), 8)
  expect_equal(     weightedMeanScore(x = v6), 8)
  expect_equal(           medianScore(x = v6), 8)
  expect_equal(             modeScore(x = v6), 8)
  expect_equal(         midrangeScore(x = v6), 8)
  expect_equal(         midhingeScore(x = v6), 8)
  expect_equal(          trimeanScore(x = v6), 8)
  expect_equal(          briskowScore(x = v6), 0)
  expect_equal(  reviewedBriskowScore(x = v6), 0)
  expect_equal(interquartileMeanScore(x = v6), 8)
  expect_equal(      weightedSumScore(x = v6), 48)
  expect_equal(           ssGseaScore(x = v6), getDefaultNaValue())
  expect_equal(             gsvaScore(x = v6), getDefaultNaValue())
  expect_equal(            plageScore(x = v6), getDefaultNaValue())
  expect_equal(                zScore(x = v6), getDefaultNaValue())
})


test_that("Summary Score functions works with length 2 vector of zeros", {
  expect_equal(             meanScore(x = z2), 0)
  expect_equal(      trimmedMeanScore(x = z2), 0)
  expect_equal(     weightedMeanScore(x = z2), 0)
  expect_equal(           medianScore(x = z2), 0)
  expect_equal(             modeScore(x = z2), 0)
  expect_equal(         midrangeScore(x = z2), 0)
  expect_equal(         midhingeScore(x = z2), 0)
  expect_equal(          trimeanScore(x = z2), 0)
  expect_equal(          briskowScore(x = z2), 0)
  expect_equal(  reviewedBriskowScore(x = z2), 0)
  expect_equal(interquartileMeanScore(x = z2), getDefaultNaValue())
  expect_equal(      weightedSumScore(x = z2), 0)
  expect_equal(           ssGseaScore(x = z2), getDefaultNaValue())
  expect_equal(             gsvaScore(x = z2), getDefaultNaValue())
  expect_equal(            plageScore(x = z2), getDefaultNaValue())
  expect_equal(                zScore(x = z2), getDefaultNaValue())
})

test_that("Summary Score functions works with length 6 vector of zeros", {
  expect_equal(             meanScore(x = z6), 0)
  expect_equal(      trimmedMeanScore(x = z6), 0)
  expect_equal(     weightedMeanScore(x = z6), 0)
  expect_equal(           medianScore(x = z6), 0)
  expect_equal(             modeScore(x = z6), 0)
  expect_equal(         midrangeScore(x = z6), 0)
  expect_equal(         midhingeScore(x = z6), 0)
  expect_equal(          trimeanScore(x = z6), 0)
  expect_equal(          briskowScore(x = z6), 0)
  expect_equal(  reviewedBriskowScore(x = z6), 0)
  expect_equal(interquartileMeanScore(x = z6), 0)
  expect_equal(      weightedSumScore(x = z6), 0)
  expect_equal(           ssGseaScore(x = z6), getDefaultNaValue())
  expect_equal(             gsvaScore(x = z6), getDefaultNaValue())
  expect_equal(            plageScore(x = z6), getDefaultNaValue())
  expect_equal(                zScore(x = z6), getDefaultNaValue())
})


test_that("Summary Score functions works with length 6 vector of NAs (`na.rm = TRUE`)", {
  #Default implementation
  # expect_equal(             meanScore(x = na6), NaN)
  # expect_equal(      trimmedMeanScore(x = na6), NaN)
  # expect_equal(     weightedMeanScore(x = na6), NaN)
  # expect_equal(           medianScore(x = na6), NA)
  # expect_equal(             modeScore(x = na6), NULL)
  # expect_equal(         midrangeScore(x = na6), NaN)
  # expect_equal(         midhingeScore(x = na6), NA_real_)
  # expect_equal(          trimeanScore(x = na6), NA)
  # expect_equal(          briskowScore(x = na6), 0)
  # expect_equal(  reviewedBriskowScore(x = na6), 0)
  # expect_equal(interquartileMeanScore(x = na6), NA)
  # expect_equal(           ssGseaScore(x = na6), NA)
  # expect_equal(             gsvaScore(x = na6), NA)
  # expect_equal(            plageScore(x = na6), NA)
  # expect_equal(                zScore(x = na6), NA)

  expect_equal(             meanScore(x = na6), getDefaultNaValue())
  expect_equal(      trimmedMeanScore(x = na6), getDefaultNaValue())
  expect_equal(     weightedMeanScore(x = na6), getDefaultNaValue())
  expect_equal(           medianScore(x = na6), getDefaultNaValue())
  expect_equal(             modeScore(x = na6), getDefaultNaValue())
  expect_equal(         midrangeScore(x = na6), getDefaultNaValue())
  expect_equal(         midhingeScore(x = na6), getDefaultNaValue())
  expect_equal(          trimeanScore(x = na6), getDefaultNaValue())
  expect_equal(          briskowScore(x = na6), getDefaultNaValue())
  expect_equal(  reviewedBriskowScore(x = na6), getDefaultNaValue())
  expect_equal(interquartileMeanScore(x = na6), getDefaultNaValue())
  expect_equal(      weightedSumScore(x = na6), getDefaultNaValue())
  expect_equal(           ssGseaScore(x = na6), getDefaultNaValue())
  expect_equal(             gsvaScore(x = na6), getDefaultNaValue())
  expect_equal(            plageScore(x = na6), getDefaultNaValue())
  expect_equal(                zScore(x = na6), getDefaultNaValue())

})

test_that("Summary Score functions works with length 6 vector of NAs (`na.rm = FALSE`)", {
  #Default implementation
  # expect_equal(             meanScore(x = na6, na.rm = FALSE), NaN)
  # expect_equal(      trimmedMeanScore(x = na6, na.rm = FALSE), NaN)
  # expect_equal(     weightedMeanScore(x = na6, na.rm = FALSE), NaN)
  # expect_equal(           medianScore(x = na6, na.rm = FALSE), NA)
  # expect_equal(             modeScore(x = na6, na.rm = FALSE), NA_character_)
  # expect_equal(         midrangeScore(x = na6, na.rm = FALSE), NaN)
  # expect_equal(         midhingeScore(x = na6, na.rm = FALSE), NA_real_)
  # expect_equal(          trimeanScore(x = na6, na.rm = FALSE), NA_real_)
  # expect_equal(          briskowScore(x = na6, na.rm = FALSE), 0)
  # expect_equal(  reviewedBriskowScore(x = na6, na.rm = FALSE), 0)
  # expect_equal(interquartileMeanScore(x = na6, na.rm = FALSE), NA)
  # expect_equal(           ssGseaScore(x = na6, na.rm = FALSE), NA)
  # expect_equal(             gsvaScore(x = na6, na.rm = FALSE), NA)
  # expect_equal(            plageScore(x = na6, na.rm = FALSE), NA)
  # expect_equal(                zScore(x = na6, na.rm = FALSE), NA)

  expect_equal(             meanScore(x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(      trimmedMeanScore(x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(     weightedMeanScore(x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(           medianScore(x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(             modeScore(x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(         midrangeScore(x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(         midhingeScore(x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(          trimeanScore(x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(          briskowScore(x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(  reviewedBriskowScore(x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(interquartileMeanScore(x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(      weightedSumScore(x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(           ssGseaScore(x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(             gsvaScore(x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(            plageScore(x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(                zScore(x = na6, na.rm = FALSE), getDefaultNaValue())
})


test_that("Summary Score functions works with length 5 vector of 3 real numbers and 2 NAs (`na.rm = TRUE`)", {
  expect_equal(             meanScore(x = m5, na.rm = TRUE), 3)
  expect_equal(      trimmedMeanScore(x = m5, na.rm = TRUE), 3)
  expect_equal(     weightedMeanScore(x = m5, na.rm = TRUE), 3)
  expect_equal(           medianScore(x = m5, na.rm = TRUE), 2)
  expect_equal(             modeScore(x = m5, na.rm = TRUE), 1)
  expect_equal(         midrangeScore(x = m5, na.rm = TRUE), 3.5)
  expect_equal(         midhingeScore(x = m5, na.rm = TRUE), 2.75)
  expect_equal(          trimeanScore(x = m5, na.rm = TRUE), 2.375)
  expect_equal(          briskowScore(x = m5, na.rm = TRUE), 0)
  expect_equal(  reviewedBriskowScore(x = m5, na.rm = TRUE), 0)
  expect_equal(interquartileMeanScore(x = m5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(      weightedSumScore(x = m5, na.rm = TRUE), 9)
  expect_equal(           ssGseaScore(x = m5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(             gsvaScore(x = m5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(            plageScore(x = m5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(                zScore(x = m5, na.rm = TRUE), getDefaultNaValue())
})

test_that("Summary Score functions works with length 5 vector of 3 real numbers and 2 NAs (`na.rm = FALSE`)", {
  expect_equal(             meanScore(x = m5, na.rm = FALSE), NaN)
  expect_equal(      trimmedMeanScore(x = m5, na.rm = FALSE), NaN)
  expect_equal(     weightedMeanScore(x = m5, na.rm = FALSE), NaN)
  expect_equal(           medianScore(x = m5, na.rm = FALSE), NA_real_)
  expect_equal(             modeScore(x = m5, na.rm = FALSE), NA_real_)
  expect_equal(         midrangeScore(x = m5, na.rm = FALSE), NaN)
  expect_equal(         midhingeScore(x = m5, na.rm = FALSE), 2.75)
  expect_equal(          trimeanScore(x = m5, na.rm = FALSE), NA_real_)
  expect_equal(          briskowScore(x = m5, na.rm = FALSE), 0)
  expect_equal(  reviewedBriskowScore(x = m5, na.rm = FALSE), 0)
  # expect_equal(interquartileMeanScore(x = m5, na.rm = FALSE), 2.4)
  expect_equal(interquartileMeanScore(x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(      weightedSumScore(x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(           ssGseaScore(x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(             gsvaScore(x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(            plageScore(x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(                zScore(x = m5, na.rm = FALSE), getDefaultNaValue())
})

