#'@include utility-functions.R
NULL

library(usethis)
library(testthat)



# Test 1-column matrices ----------------------------------------------

#matrix of numbers
v1 = c(1)
v2 = c(1,4)
v3 = c(2,6,1)
v4 = c(3,5,1,3)
v5 = c(1,4,4,2,9)
v6 = c(8,8,8,8,8,8)
v7 = c(1,1,4,4,3,2,1)
v8 = c(1,1,4,4,3,2,1,7)
v1 = matrix(v1, ncol = 1)
v2 = matrix(v2, ncol = 1)
v3 = matrix(v3, ncol = 1)
v4 = matrix(v4, ncol = 1)
v5 = matrix(v5, ncol = 1)
v6 = matrix(v6, ncol = 1)
v7 = matrix(v7, ncol = 1)
v8 = matrix(v8, ncol = 1)


#zeros
z1 = 0
z2 = c(0,0)
z6 = c(0,0,0,0,0,0)
z1 = matrix(z1, ncol = 1)
z2 = matrix(z2, ncol = 1)
z6 = matrix(z6, ncol = 1)


#NAs
na1 = NA
na2 = c(NA,NA)
na6 = c(NA,NA,NA,NA,NA,NA)
na1 = matrix(na1, ncol = 1)
na2 = matrix(na2, ncol = 1)
na6 = matrix(na6, ncol = 1)

#numbers and NAs
m2 = c(2, NA)
m3 = c(2, NA, 4)
m4 = c(2, NA, 3, 4)
m5 = c(2, 6, NA, NA, 1)
m2 = matrix(m2, ncol = 1)
m3 = matrix(m3, ncol = 1)
m4 = matrix(m4, ncol = 1)
m5 = matrix(m5, ncol = 1)

#gene signatures
i1 = 1
i2 = c(1,2)
i3 = seq_len(length.out = 3)
i4 = seq_len(length.out = 4)
i5 = seq_len(length.out = 5)
i6 = seq_len(length.out = 6)
i1r = c(1, sample(x = seq_len(100), size = 19))
iwom = 20

## Test 1-by-1 matrices ----------------------------------------------

test_that("Summary Scores functions works with 1-by-1 matrix and signature with 1 matching element", {
  expect_equal(           sumScorer(x = v1, i = i1), 1)
  expect_equal(   weightedSumScorer(x = v1, i = i1), 1)
  expect_equal(          meanScorer(x = v1, i = i1), 1)
  expect_equal(   trimmedMeanScorer(x = v1, i = i1), 1)
  expect_equal(  weightedMeanScorer(x = v1, i = i1), 1)
  expect_equal(        medianScorer(x = v1, i = i1), 1)
  expect_equal(          modeScorer(x = v1, i = i1), 1)
  expect_equal(      midrangeScorer(x = v1, i = i1), 1)
  expect_equal(      midhingeScorer(x = v1, i = i1), 1)
  expect_equal(       trimeanScorer(x = v1, i = i1), 1)
  expect_equal(           iqrScorer(x = v1, i = i1), 0)
  expect_equal(           iqmScorer(x = v1, i = i1), getDefaultNaValue())
  expect_equal(           madScorer(x = v1, i = i1), 0)
  expect_equal(           aadScorer(x = v1, i = i1), 0)
  expect_equal(        ssgseaScorer(x = v1, i = i1), getDefaultNaValue())
  expect_equal(          gsvaScorer(x = v1, i = i1), getDefaultNaValue())
  expect_equal(         plageScorer(x = v1, i = i1), getDefaultNaValue())
  expect_equal(        zscoreScorer(x = v1, i = i1), getDefaultNaValue())
})

test_that("Summary Scores functions works with 1-by-1 matrix and signature with 2 elements", {
  expect_error(             sumScorer(x = v1, i = i2))
  expect_error(     weightedSumScorer(x = v1, i = i2))
  expect_error(            meanScorer(x = v1, i = i2))
  expect_error(     trimmedMeanScorer(x = v1, i = i2))
  expect_error(    weightedMeanScorer(x = v1, i = i2))
  expect_error(          medianScorer(x = v1, i = i2))
  expect_error(            modeScorer(x = v1, i = i2))
  expect_error(        midrangeScorer(x = v1, i = i2))
  expect_error(        midhingeScorer(x = v1, i = i2))
  expect_error(         trimeanScorer(x = v1, i = i2))
  expect_error(             iqrScorer(x = v1, i = i2))
  expect_error(             iqmScorer(x = v1, i = i2))
  expect_error(             madScorer(x = v1, i = i2))
  expect_error(             aadScorer(x = v1, i = i2))
  expect_equal(          ssgseaScorer(x = v1, i = i2), getDefaultNaValue())
  expect_equal(            gsvaScorer(x = v1, i = i2), getDefaultNaValue())
  expect_equal(           plageScorer(x = v1, i = i2), getDefaultNaValue())
  expect_equal(          zscoreScorer(x = v1, i = i2), getDefaultNaValue())
})

test_that("Summary Scores functions works with 1-by-1 matrix and signature with 20 elements (1 matching)", {
  expect_error(         sumScorer(x = v1, i = i1r))
  expect_error( weightedSumScorer(x = v1, i = i1r))
  expect_error(        meanScorer(x = v1, i = i1r))
  expect_error( trimmedMeanScorer(x = v1, i = i1r))
  expect_error(weightedMeanScorer(x = v1, i = i1r))
  expect_error(      medianScorer(x = v1, i = i1r))
  expect_error(        modeScorer(x = v1, i = i1r))
  expect_error(    midrangeScorer(x = v1, i = i1r))
  expect_error(    midhingeScorer(x = v1, i = i1r))
  expect_error(     trimeanScorer(x = v1, i = i1r))
  expect_error(         iqrScorer(x = v1, i = i1r))
  expect_error(         iqmScorer(x = v1, i = i1r))
  expect_error(         madScorer(x = v1, i = i1r))
  expect_error(         aadScorer(x = v1, i = i1r))
  expect_equal(      ssgseaScorer(x = v1, i = i1r), getDefaultNaValue())
  expect_equal(        gsvaScorer(x = v1, i = i1r), getDefaultNaValue())
  expect_equal(       plageScorer(x = v1, i = i1r), getDefaultNaValue())
  expect_equal(      zscoreScorer(x = v1, i = i1r), getDefaultNaValue())
})

test_that("Summary Scores functions works with 1-by-1 matrix and signature without matching elements", {
  expect_error(         sumScorer(x = v1, i = iwom))
  expect_error( weightedSumScorer(x = v1, i = iwom))
  expect_error(        meanScorer(x = v1, i = iwom))
  expect_error( trimmedMeanScorer(x = v1, i = iwom))
  expect_error(weightedMeanScorer(x = v1, i = iwom))
  expect_error(      medianScorer(x = v1, i = iwom))
  expect_error(        modeScorer(x = v1, i = iwom))
  expect_error(    midrangeScorer(x = v1, i = iwom))
  expect_error(    midhingeScorer(x = v1, i = iwom))
  expect_error(     trimeanScorer(x = v1, i = iwom))
  expect_error(         iqrScorer(x = v1, i = iwom))
  expect_error(         iqmScorer(x = v1, i = iwom))
  expect_error(         madScorer(x = v1, i = iwom))
  expect_error(         aadScorer(x = v1, i = iwom))
  expect_equal(      ssgseaScorer(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(        gsvaScorer(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(       plageScorer(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(      zscoreScorer(x = v1, i = iwom), getDefaultNaValue())
})

## Test 2-by-1 matrices ----------------------------------------------

test_that("Summary Scores functions works with 2-by-1 matrix and signature with 1 matching element", {
  expect_equal(         sumScorer(x = v2, i = i1), 1)
  expect_equal( weightedSumScorer(x = v2, i = i1), 1)
  expect_equal(        meanScorer(x = v2, i = i1), 1)
  expect_equal( trimmedMeanScorer(x = v2, i = i1), 1)
  expect_equal(weightedMeanScorer(x = v2, i = i1), 1)
  expect_equal(      medianScorer(x = v2, i = i1), 1)
  expect_equal(        modeScorer(x = v2, i = i1), 1)
  expect_equal(    midrangeScorer(x = v2, i = i1), 1)
  expect_equal(    midhingeScorer(x = v2, i = i1), 1)
  expect_equal(     trimeanScorer(x = v2, i = i1), 1)
  expect_equal(         iqrScorer(x = v2, i = i1), 0)
  expect_equal(         iqmScorer(x = v2, i = i1), getDefaultNaValue())
  expect_equal(         madScorer(x = v2, i = i1), 0)
  expect_equal(         aadScorer(x = v2, i = i1), 0)
  expect_equal(      ssgseaScorer(x = v2, i = i1), getDefaultNaValue())
  expect_equal(        gsvaScorer(x = v2, i = i1), getDefaultNaValue())
  expect_equal(       plageScorer(x = v2, i = i1), getDefaultNaValue())
  expect_equal(      zscoreScorer(x = v2, i = i1), getDefaultNaValue())
})


test_that("Summary Scores functions works with 2-by-1 matrix and signature with 2 matching elements", {
  expect_equal(         sumScorer(x = v2, i = i2), 5)
  expect_equal( weightedSumScorer(x = v2, i = i2), 5)
  expect_equal(        meanScorer(x = v2, i = i2), 2.5)
  expect_equal( trimmedMeanScorer(x = v2, i = i2), 2.5)
  expect_equal(weightedMeanScorer(x = v2, i = i2), 2.5)
  expect_equal(      medianScorer(x = v2, i = i2), 2.5)
  expect_equal(        modeScorer(x = v2, i = i2), 1)
  expect_equal(    midrangeScorer(x = v2, i = i2), 2.5)
  expect_equal(    midhingeScorer(x = v2, i = i2), 2.5)
  expect_equal(     trimeanScorer(x = v2, i = i2), 2.5)
  expect_equal(         iqrScorer(x = v2, i = i2), 1.5)
  expect_equal(         iqmScorer(x = v2, i = i2), getDefaultNaValue())
  expect_equal(         madScorer(x = v2, i = i2), 2.2239)
  expect_equal(         aadScorer(x = v2, i = i2), 1.5)
  expect_equal(      ssgseaScorer(x = v2, i = i2), getDefaultNaValue())
  expect_equal(        gsvaScorer(x = v2, i = i2), getDefaultNaValue())
  expect_equal(       plageScorer(x = v2, i = i2), getDefaultNaValue())
  expect_equal(      zscoreScorer(x = v2, i = i2), getDefaultNaValue())
})

## Test 3-by-1 matrices ----------------------------------------------

test_that("Summary Scores functions works with 3-by-1 matrix and signature with 3 matching elements", {
  expect_equal(         sumScorer(x = v3, i = i3), 9)
  expect_equal( weightedSumScorer(x = v3, i = i3), 9)
  expect_equal(        meanScorer(x = v3, i = i3), 3)
  expect_equal( trimmedMeanScorer(x = v3, i = i3), 3)
  expect_equal(weightedMeanScorer(x = v3, i = i3), 3)
  expect_equal(      medianScorer(x = v3, i = i3), 2)
  expect_equal(        modeScorer(x = v3, i = i3), 1)
  expect_equal(    midrangeScorer(x = v3, i = i3), 3.5)
  expect_equal(    midhingeScorer(x = v3, i = i3), 2.75)
  expect_equal(     trimeanScorer(x = v3, i = i3), 2.375)
  expect_equal(         iqrScorer(x = v3, i = i3), 2.5)
  expect_equal(         iqmScorer(x = v3, i = i3), getDefaultNaValue())
  expect_equal(         madScorer(x = v3, i = i3), 1.4826)
  expect_equal(         aadScorer(x = v3, i = i3), 1.66666667)
  expect_equal(      ssgseaScorer(x = v3, i = i3), getDefaultNaValue())
  expect_equal(        gsvaScorer(x = v3, i = i3), getDefaultNaValue())
  expect_equal(       plageScorer(x = v3, i = i3), getDefaultNaValue())
  expect_equal(      zscoreScorer(x = v3, i = i3), getDefaultNaValue())
})

## Test 4-by-1 matrices ----------------------------------------------

test_that("Summary Scores functions works with 4-by-1 matrix and signature with 4 matching elements", {
  expect_equal(         sumScorer(x = v4, i = i4), 12)
  expect_equal( weightedSumScorer(x = v4, i = i4), 12)
  expect_equal(        meanScorer(x = v4, i = i4), 3)
  expect_equal( trimmedMeanScorer(x = v4, i = i4), 3)
  expect_equal(weightedMeanScorer(x = v4, i = i4), 3)
  expect_equal(      medianScorer(x = v4, i = i4), 3)
  expect_equal(        modeScorer(x = v4, i = i4), 3)
  expect_equal(    midrangeScorer(x = v4, i = i4), 3)
  expect_equal(    midhingeScorer(x = v4, i = i4), 3)
  expect_equal(     trimeanScorer(x = v4, i = i4), 3)
  expect_equal(         iqrScorer(x = v4, i = i4), 1)
  expect_equal(         iqmScorer(x = v4, i = i4), 3)
  expect_equal(         madScorer(x = v4, i = i4), 1.4826)
  expect_equal(         aadScorer(x = v4, i = i4), 1)
  expect_equal(      ssgseaScorer(x = v4, i = i4), getDefaultNaValue())
  expect_equal(        gsvaScorer(x = v4, i = i4), getDefaultNaValue())
  expect_equal(       plageScorer(x = v4, i = i4), getDefaultNaValue())
  expect_equal(      zscoreScorer(x = v4, i = i4), getDefaultNaValue())
})

## Test 5-by-1 matrices ----------------------------------------------

test_that("Summary Scores functions works with 5-by-1 matrix and signature with 5 matching elements", {
  expect_equal(         sumScorer(x = v5, i = i5), 20                 )
  expect_equal( weightedSumScorer(x = v5, i = i5), 20                 )
  expect_equal(        meanScorer(x = v5, i = i5), 4                  )
  expect_equal( trimmedMeanScorer(x = v5, i = i5), 4                  )
  expect_equal(weightedMeanScorer(x = v5, i = i5), 4                  )
  expect_equal(      medianScorer(x = v5, i = i5), 4                  )
  expect_equal(        modeScorer(x = v5, i = i5), 4                  )
  expect_equal(    midrangeScorer(x = v5, i = i5), 5                  )
  expect_equal(    midhingeScorer(x = v5, i = i5), 3                  )
  expect_equal(     trimeanScorer(x = v5, i = i5), 3.5                )
  expect_equal(         iqrScorer(x = v5, i = i5), 2                  )
  expect_equal(         iqmScorer(x = v5, i = i5), 3.4                )
  expect_equal(         madScorer(x = v5, i = i5), 2.9652             )
  expect_equal(         aadScorer(x = v5, i = i5), 2                  )
  expect_equal(      ssgseaScorer(x = v5, i = i5), getDefaultNaValue())
  expect_equal(        gsvaScorer(x = v5, i = i5), getDefaultNaValue())
  expect_equal(       plageScorer(x = v5, i = i5), getDefaultNaValue())
  expect_equal(      zscoreScorer(x = v5, i = i5), getDefaultNaValue())
})


## Test 6-by-1 matrices ----------------------------------------------

test_that("Summary Scores functions works with 6-by-1 matrix of equal elements and signature with 6 matching elements", {
  expect_equal(         sumScorer(x = v6, i = i6), 48                 )
  expect_equal( weightedSumScorer(x = v6, i = i6), 48                 )
  expect_equal(        meanScorer(x = v6, i = i6), 8                  )
  expect_equal( trimmedMeanScorer(x = v6, i = i6), 8                  )
  expect_equal(weightedMeanScorer(x = v6, i = i6), 8                  )
  expect_equal(      medianScorer(x = v6, i = i6), 8                  )
  expect_equal(        modeScorer(x = v6, i = i6), 8                  )
  expect_equal(    midrangeScorer(x = v6, i = i6), 8                  )
  expect_equal(    midhingeScorer(x = v6, i = i6), 8                  )
  expect_equal(     trimeanScorer(x = v6, i = i6), 8                  )
  expect_equal(         iqrScorer(x = v6, i = i6), 0                  )
  expect_equal(         iqmScorer(x = v6, i = i6), 8                  )
  expect_equal(         madScorer(x = v6, i = i6), 0                  )
  expect_equal(         aadScorer(x = v6, i = i6), 0                  )
  expect_equal(      ssgseaScorer(x = v6, i = i6), getDefaultNaValue())
  expect_equal(        gsvaScorer(x = v6, i = i6), getDefaultNaValue())
  expect_equal(       plageScorer(x = v6, i = i6), getDefaultNaValue())
  expect_equal(      zscoreScorer(x = v6, i = i6), getDefaultNaValue())
})


## Test matrices of zeros ----------------------------------------------

test_that("Summary Scores functions works with 2-by-1 matrix of zeros and signature with 2 matching elements", {
  expect_equal(         sumScorer(x = z2, i = i2), 0)
  expect_equal( weightedSumScorer(x = z2, i = i2), 0)
  expect_equal(        meanScorer(x = z2, i = i2), 0)
  expect_equal( trimmedMeanScorer(x = z2, i = i2), 0)
  expect_equal(weightedMeanScorer(x = z2, i = i2), 0)
  expect_equal(      medianScorer(x = z2, i = i2), 0)
  expect_equal(        modeScorer(x = z2, i = i2), 0)
  expect_equal(    midrangeScorer(x = z2, i = i2), 0)
  expect_equal(    midhingeScorer(x = z2, i = i2), 0)
  expect_equal(     trimeanScorer(x = z2, i = i2), 0)
  expect_equal(         iqrScorer(x = z2, i = i2), 0)
  expect_equal(         iqmScorer(x = z2, i = i2), getDefaultNaValue())
  expect_equal(         madScorer(x = z2, i = i2), 0)
  expect_equal(         aadScorer(x = z2, i = i2), 0)
  expect_equal(      ssgseaScorer(x = z2, i = i2), getDefaultNaValue())
  expect_equal(        gsvaScorer(x = z2, i = i2), getDefaultNaValue())
  expect_equal(       plageScorer(x = z2, i = i2), getDefaultNaValue())
  expect_equal(      zscoreScorer(x = z2, i = i2), getDefaultNaValue())
})

test_that("Summary Scores functions works with 6-by-1 matrix of zeros and signature with 6 matching elements", {
  expect_equal(         sumScorer(x = z6, i = i6), 0)
  expect_equal( weightedSumScorer(x = z6, i = i6), 0)
  expect_equal(        meanScorer(x = z6, i = i6), 0)
  expect_equal( trimmedMeanScorer(x = z6, i = i6), 0)
  expect_equal(weightedMeanScorer(x = z6, i = i6), 0)
  expect_equal(      medianScorer(x = z6, i = i6), 0)
  expect_equal(        modeScorer(x = z6, i = i6), 0)
  expect_equal(    midrangeScorer(x = z6, i = i6), 0)
  expect_equal(    midhingeScorer(x = z6, i = i6), 0)
  expect_equal(     trimeanScorer(x = z6, i = i6), 0)
  expect_equal(         iqrScorer(x = z6, i = i6), 0)
  expect_equal(         iqmScorer(x = z6, i = i6), 0)
  expect_equal(         madScorer(x = z6, i = i6), 0)
  expect_equal(         aadScorer(x = z6, i = i6), 0)
  expect_equal(      ssgseaScorer(x = z6, i = i6), getDefaultNaValue())
  expect_equal(        gsvaScorer(x = z6, i = i6), getDefaultNaValue())
  expect_equal(       plageScorer(x = z6, i = i6), getDefaultNaValue())
  expect_equal(      zscoreScorer(x = z6, i = i6), getDefaultNaValue())
})

## Test matrices of NAs ----------------------------------------------

test_that("Summary Scores functions works with 6-by-1 matrix of NAs (`na.rm = TRUE`) and signature with 6 matching elements", {
  # expect_equal(         sumScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal( weightedSumScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal(        meanScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal( trimmedMeanScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal(weightedMeanScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal(      medianScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal(        modeScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal(    midrangeScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal(    midhingeScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal(     trimeanScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal(         iqrScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal(         iqmScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal(         madScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal(         aadScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal(      ssgseaScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal(        gsvaScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal(       plageScorer(x = na6, i = i6), getDefaultNaValue())
  # expect_equal(      zscoreScorer(x = na6, i = i6), getDefaultNaValue())
})

test_that("Summary Scores functions works with 6-by-1 matrix of NAs (`na.rm = FALSE`) and signature with 6 matching elements", {
  # expect_equal(         sumScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal( weightedSumScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal(        meanScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal( trimmedMeanScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal(weightedMeanScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal(      medianScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal(        modeScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal(    midrangeScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal(    midhingeScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal(     trimeanScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal(         iqrScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal(         iqmScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal(         madScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal(         aadScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal(      ssgseaScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal(        gsvaScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal(       plageScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  # expect_equal(      zscoreScorer(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
})

## Test matrices with numbers and NAs ----------------------------------------------

test_that("Summary Scores functions works with 5-by-1 matrix containing 3 real numbers and 2 NAs (`na.rm = TRUE`) and signature with 5 matching elements", {
  expect_equal(         sumScorer(x = m5, i = i5, na.rm = TRUE), 9                  )
  expect_equal( weightedSumScorer(x = m5, i = i5, na.rm = TRUE), 9                  )
  expect_equal(        meanScorer(x = m5, i = i5, na.rm = TRUE), 3                  )
  expect_equal( trimmedMeanScorer(x = m5, i = i5, na.rm = TRUE), 3                  )
  expect_equal(weightedMeanScorer(x = m5, i = i5, na.rm = TRUE), 3                  )
  expect_equal(      medianScorer(x = m5, i = i5, na.rm = TRUE), 2                  )
  expect_equal(        modeScorer(x = m5, i = i5, na.rm = TRUE), 1                  )
  expect_equal(    midrangeScorer(x = m5, i = i5, na.rm = TRUE), 3.5                )
  expect_equal(    midhingeScorer(x = m5, i = i5, na.rm = TRUE), 2.75               )
  expect_equal(     trimeanScorer(x = m5, i = i5, na.rm = TRUE), 2.375              )
  expect_equal(         iqrScorer(x = m5, i = i5, na.rm = TRUE), 2.5                )
  expect_equal(         iqmScorer(x = m5, i = i5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(         madScorer(x = m5, i = i5, na.rm = TRUE), 1.4826             )
  expect_equal(         aadScorer(x = m5, i = i5, na.rm = TRUE), 1.66666667         )
  expect_equal(      ssgseaScorer(x = m5, i = i5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(        gsvaScorer(x = m5, i = i5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(       plageScorer(x = m5, i = i5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(      zscoreScorer(x = m5, i = i5, na.rm = TRUE), getDefaultNaValue())
})

test_that("Summary Scores functions works with 5-by-1 matrix containing 3 real numbers and 2 NAs (`na.rm = FALSE`) and signature with 5 matching elements", {
  expect_equal(         sumScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal( weightedSumScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(        meanScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal( trimmedMeanScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(weightedMeanScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(      medianScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(        modeScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(    midrangeScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(    midhingeScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(     trimeanScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(         iqrScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(         iqmScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(         madScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(         aadScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(      ssgseaScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(        gsvaScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(       plageScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(      zscoreScorer(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
})



# Test 2-column matrices ----------------------------------------------

#matrix of numbers
v1 = c(1)
v2 = c(1,4)
v3 = c(2,6,1)
v4 = c(3,5,1,3)
v5 = c(1,4,4,2,9)
v6 = c(8,8,8,8,8,8)
v7 = c(1,1,4,4,3,2,1)
v8 = c(1,1,4,4,3,2,1,7)
v1 = matrix(c(v1, v1), ncol = 2)
v2 = matrix(c(v2, v2), ncol = 2)
v3 = matrix(c(v3, v3), ncol = 2)
v4 = matrix(c(v4, v4), ncol = 2)
v5 = matrix(c(v5, v5), ncol = 2)
v6 = matrix(c(v6, v6), ncol = 2)
v7 = matrix(c(v7, v7), ncol = 2)
v8 = matrix(c(v8, v8), ncol = 2)


#zeros
z1 = 0
z2 = c(0,0)
z6 = c(0,0,0,0,0,0)
z1 = matrix(c(z1, z1), ncol = 2)
z2 = matrix(c(z2, z2), ncol = 2)
z6 = matrix(c(z6, z6), ncol = 2)


#NAs
na1 = NA
na2 = c(NA,NA)
na6 = c(NA,NA,NA,NA,NA,NA)
na1 = matrix(c(na1, na1), ncol = 2)
na2 = matrix(c(na2, na2), ncol = 2)
na6 = matrix(c(na6, na6), ncol = 2)

#numbers and NAs
m2 = c(2, NA)
m3 = c(2, NA, 4)
m4 = c(2, NA, 3, 4)
m5 = c(2, 6, NA, NA, 1)
m6a= c(6, 1, 1, NA, 3, 2)
m6b= c(2, 6,NA,  1, 4, 1)
m2 = matrix(c(m2, m2), ncol = 2)
m3 = matrix(c(m3, m3), ncol = 2)
m4 = matrix(c(m4, m4), ncol = 2)
m5 = matrix(c(m5, m5), ncol = 2)
m6 = matrix(c(m6a, m6b), ncol = 2)

#gene signatures
i1 = 1
i2 = c(1,2)
i3 = seq_len(length.out = 3)
i4 = seq_len(length.out = 4)
i5 = seq_len(length.out = 5)
i6 = seq_len(length.out = 6)
i1r = c(1, sample(x = seq_len(100), size = 19))
iwom = 20


## Test 1-by-2 matrices ----------------------------------------------

test_that("Summary Scores functions works with 1-by-2 matrix and signature with 1 matching element", {
  expect_equal(         sumScorer(x = v1, i = i1), rep(1, 2))
  expect_equal( weightedSumScorer(x = v1, i = i1), rep(1, 2))
  expect_equal(        meanScorer(x = v1, i = i1), rep(1, 2))
  expect_equal( trimmedMeanScorer(x = v1, i = i1), rep(1, 2))
  expect_equal(weightedMeanScorer(x = v1, i = i1), rep(1, 2))
  expect_equal(      medianScorer(x = v1, i = i1), rep(1, 2))
  expect_equal(        modeScorer(x = v1, i = i1), rep(1, 2))
  expect_equal(    midrangeScorer(x = v1, i = i1), rep(1, 2))
  expect_equal(    midhingeScorer(x = v1, i = i1), rep(1, 2))
  expect_equal(     trimeanScorer(x = v1, i = i1), rep(1, 2))
  expect_equal(         iqrScorer(x = v1, i = i1), rep(0, 2))
  expect_equal(         iqmScorer(x = v1, i = i1), rep(getDefaultNaValue(), 2))
  expect_equal(         madScorer(x = v1, i = i1), rep(0, 2))
  expect_equal(         aadScorer(x = v1, i = i1), rep(0, 2))
  expect_equal(      ssgseaScorer(x = v1, i = i1), rep(getDefaultNaValue(), 2))
  expect_equal(        gsvaScorer(x = v1, i = i1), rep(getDefaultNaValue(), 2))
  expect_equal(       plageScorer(x = v1, i = i1), rep(getDefaultNaValue(), 2))
  expect_equal(      zscoreScorer(x = v1, i = i1), rep(getDefaultNaValue(), 2))
})

test_that("Summary Scores functions works with 1-by-2 matrix and signature with 2 elements (1 matching)", {
  expect_error(         sumScorer(x = v1, i = i2))
  expect_error( weightedSumScorer(x = v1, i = i2))
  expect_error(        meanScorer(x = v1, i = i2))
  expect_error( trimmedMeanScorer(x = v1, i = i2))
  expect_error(weightedMeanScorer(x = v1, i = i2))
  expect_error(      medianScorer(x = v1, i = i2))
  expect_error(        modeScorer(x = v1, i = i2))
  expect_error(    midrangeScorer(x = v1, i = i2))
  expect_error(    midhingeScorer(x = v1, i = i2))
  expect_error(     trimeanScorer(x = v1, i = i2))
  expect_error(         iqrScorer(x = v1, i = i2))
  expect_error(         iqmScorer(x = v1, i = i2))
  expect_error(         madScorer(x = v1, i = i2))
  expect_error(         aadScorer(x = v1, i = i2))
  expect_equal(      ssgseaScorer(x = v1, i = i2), rep(getDefaultNaValue(), 2))
  expect_equal(        gsvaScorer(x = v1, i = i2), rep(getDefaultNaValue(), 2))
  expect_equal(       plageScorer(x = v1, i = i2), rep(getDefaultNaValue(), 2))
  expect_equal(      zscoreScorer(x = v1, i = i2), rep(getDefaultNaValue(), 2))
})

test_that("Summary Scores functions works with 1-by-2 matrix and signature with 20 elements (1 matching)", {
  expect_error(         sumScorer(x = v1, i = i1r))
  expect_error( weightedSumScorer(x = v1, i = i1r))
  expect_error(        meanScorer(x = v1, i = i1r))
  expect_error( trimmedMeanScorer(x = v1, i = i1r))
  expect_error(weightedMeanScorer(x = v1, i = i1r))
  expect_error(      medianScorer(x = v1, i = i1r))
  expect_error(        modeScorer(x = v1, i = i1r))
  expect_error(    midrangeScorer(x = v1, i = i1r))
  expect_error(    midhingeScorer(x = v1, i = i1r))
  expect_error(     trimeanScorer(x = v1, i = i1r))
  expect_error(         iqrScorer(x = v1, i = i1r))
  expect_error(         iqmScorer(x = v1, i = i1r))
  expect_error(         madScorer(x = v1, i = i1r))
  expect_error(         aadScorer(x = v1, i = i1r))
  expect_equal(      ssgseaScorer(x = v1, i = i1r), rep(getDefaultNaValue(), 2))
  expect_equal(        gsvaScorer(x = v1, i = i1r), rep(getDefaultNaValue(), 2))
  expect_equal(       plageScorer(x = v1, i = i1r), rep(getDefaultNaValue(), 2))
  expect_equal(      zscoreScorer(x = v1, i = i1r), rep(getDefaultNaValue(), 2))
})

test_that("Summary Scores functions works with 1-by-2 matrix and signature without matching elements", {
  # expect_equal(         sumScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal( weightedSumScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal(        meanScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal( trimmedMeanScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal(weightedMeanScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal(      medianScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal(        modeScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal(    midrangeScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal(    midhingeScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal(     trimeanScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal(         iqrScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal(         iqmScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal(         madScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal(         aadScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal(      ssgseaScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal(        gsvaScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal(       plageScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
  # expect_equal(      zscoreScorer(x = v1, i = iwom), rep(getDefaultNaValue(), 2))
})

## Test 2-by-2 matrices ----------------------------------------------

test_that("Summary Scores functions works with 2-by-2 matrix and signature with 1 matching element", {
  expect_equal(         sumScorer(x = v2, i = i1), rep(1, 2))
  expect_equal( weightedSumScorer(x = v2, i = i1), rep(1, 2))
  expect_equal(        meanScorer(x = v2, i = i1), rep(1, 2))
  expect_equal( trimmedMeanScorer(x = v2, i = i1), rep(1, 2))
  expect_equal(weightedMeanScorer(x = v2, i = i1), rep(1, 2))
  expect_equal(      medianScorer(x = v2, i = i1), rep(1, 2))
  expect_equal(        modeScorer(x = v2, i = i1), rep(1, 2))
  expect_equal(    midrangeScorer(x = v2, i = i1), rep(1, 2))
  expect_equal(    midhingeScorer(x = v2, i = i1), rep(1, 2))
  expect_equal(     trimeanScorer(x = v2, i = i1), rep(1, 2))
  expect_equal(         iqrScorer(x = v2, i = i1), rep(0, 2))
  expect_equal(         iqmScorer(x = v2, i = i1), rep(getDefaultNaValue(), 2))
  expect_equal(         madScorer(x = v2, i = i1), rep(0, 2))
  expect_equal(         aadScorer(x = v2, i = i1), rep(0, 2))
  expect_equal(      ssgseaScorer(x = v2, i = i1), rep(getDefaultNaValue(), 2))
  expect_equal(        gsvaScorer(x = v2, i = i1), rep(getDefaultNaValue(), 2))
  expect_equal(       plageScorer(x = v2, i = i1), rep(getDefaultNaValue(), 2))
  expect_equal(      zscoreScorer(x = v2, i = i1), rep(getDefaultNaValue(), 2))
})


test_that("Summary Scores functions works with 2-by-2 matrix and signature with 2 matching elements", {
  expect_equal(         sumScorer(x = v2, i = i2), rep(5, 2))
  expect_equal( weightedSumScorer(x = v2, i = i2), rep(5, 2))
  expect_equal(        meanScorer(x = v2, i = i2), rep(2.5, 2))
  expect_equal( trimmedMeanScorer(x = v2, i = i2), rep(2.5, 2))
  expect_equal(weightedMeanScorer(x = v2, i = i2), rep(2.5, 2))
  expect_equal(      medianScorer(x = v2, i = i2), rep(2.5, 2))
  expect_equal(        modeScorer(x = v2, i = i2), rep(1, 2))
  expect_equal(    midrangeScorer(x = v2, i = i2), rep(2.5, 2))
  expect_equal(    midhingeScorer(x = v2, i = i2), rep(2.5, 2))
  expect_equal(     trimeanScorer(x = v2, i = i2), rep(2.5, 2))
  expect_equal(         iqrScorer(x = v2, i = i2), rep(1.5, 2))
  expect_equal(         iqmScorer(x = v2, i = i2), rep(getDefaultNaValue(), 2))
  expect_equal(         madScorer(x = v2, i = i2), rep(2.2239, 2))
  expect_equal(         aadScorer(x = v2, i = i2), rep(1.5, 2))
  expect_equal(      ssgseaScorer(x = v2, i = i2), rep(getDefaultNaValue(), 2))
  expect_equal(        gsvaScorer(x = v2, i = i2), rep(getDefaultNaValue(), 2))
  expect_equal(       plageScorer(x = v2, i = i2), rep(getDefaultNaValue(), 2))
  expect_equal(      zscoreScorer(x = v2, i = i2), rep(getDefaultNaValue(), 2))
})

## Test 3-by-2 matrices ----------------------------------------------
test_that("Summary Scores functions works with 3-by-2 matrix and signature with 3 matching elements", {
  expect_equal(         sumScorer(x = v3, i = i3), rep(9                  ,2))
  expect_equal( weightedSumScorer(x = v3, i = i3), rep(9                  ,2))
  expect_equal(        meanScorer(x = v3, i = i3), rep(3                  ,2))
  expect_equal( trimmedMeanScorer(x = v3, i = i3), rep(3                  ,2))
  expect_equal(weightedMeanScorer(x = v3, i = i3), rep(3                  ,2))
  expect_equal(      medianScorer(x = v3, i = i3), rep(2                  ,2))
  expect_equal(        modeScorer(x = v3, i = i3), rep(1                  ,2))
  expect_equal(    midrangeScorer(x = v3, i = i3), rep(3.5                ,2))
  expect_equal(    midhingeScorer(x = v3, i = i3), rep(2.75               ,2))
  expect_equal(     trimeanScorer(x = v3, i = i3), rep(2.375              ,2))
  expect_equal(         iqrScorer(x = v3, i = i3), rep(2.5                ,2))
  expect_equal(         iqmScorer(x = v3, i = i3), rep(getDefaultNaValue(),2))
  expect_equal(         madScorer(x = v3, i = i3), rep(1.4826             ,2))
  expect_equal(         aadScorer(x = v3, i = i3), rep(1.66666667         ,2))
  expect_equal(      ssgseaScorer(x = v3, i = i3), rep(getDefaultNaValue(),2))
  expect_equal(        gsvaScorer(x = v3, i = i3), rep(getDefaultNaValue(),2))
  expect_equal(       plageScorer(x = v3, i = i3), rep(getDefaultNaValue(),2))
  expect_equal(      zscoreScorer(x = v3, i = i3), rep(getDefaultNaValue(),2))
})

## Test 4-by-2 matrices ----------------------------------------------

test_that("Summary Scores functions works with 4-by-2 matrix and signature with 4 matching elements", {
  expect_equal(         sumScorer(x = v4, i = i4), rep(12                  ,2))
  expect_equal( weightedSumScorer(x = v4, i = i4), rep(12                  ,2))
  expect_equal(        meanScorer(x = v4, i = i4), rep(3                   ,2))
  expect_equal( trimmedMeanScorer(x = v4, i = i4), rep(3                   ,2))
  expect_equal(weightedMeanScorer(x = v4, i = i4), rep(3                   ,2))
  expect_equal(      medianScorer(x = v4, i = i4), rep(3                   ,2))
  expect_equal(        modeScorer(x = v4, i = i4), rep(3                   ,2))
  expect_equal(    midrangeScorer(x = v4, i = i4), rep(3                   ,2))
  expect_equal(    midhingeScorer(x = v4, i = i4), rep(3                   ,2))
  expect_equal(     trimeanScorer(x = v4, i = i4), rep(3                   ,2))
  expect_equal(         iqrScorer(x = v4, i = i4), rep(1                   ,2))
  expect_equal(         iqmScorer(x = v4, i = i4), rep(3                   ,2))
  expect_equal(         madScorer(x = v4, i = i4), rep(1.4826              ,2))
  expect_equal(         aadScorer(x = v4, i = i4), rep(1                   ,2))
  expect_equal(      ssgseaScorer(x = v4, i = i4), rep(getDefaultNaValue() ,2))
  expect_equal(        gsvaScorer(x = v4, i = i4), rep(getDefaultNaValue() ,2))
  expect_equal(       plageScorer(x = v4, i = i4), rep(getDefaultNaValue() ,2))
  expect_equal(      zscoreScorer(x = v4, i = i4), rep(getDefaultNaValue() ,2))
})

## Test 5-by-2 matrices ----------------------------------------------

test_that("Summary Scores functions works with 5-by-2 matrix and signature with 5 matching elements", {
  expect_equal(         sumScorer(x = v5, i = i5), rep(20                  ,2))
  expect_equal( weightedSumScorer(x = v5, i = i5), rep(20                  ,2))
  expect_equal(        meanScorer(x = v5, i = i5), rep(4                   ,2))
  expect_equal( trimmedMeanScorer(x = v5, i = i5), rep(4                   ,2))
  expect_equal(weightedMeanScorer(x = v5, i = i5), rep(4                   ,2))
  expect_equal(      medianScorer(x = v5, i = i5), rep(4                   ,2))
  expect_equal(        modeScorer(x = v5, i = i5), rep(4                   ,2))
  expect_equal(    midrangeScorer(x = v5, i = i5), rep(5                   ,2))
  expect_equal(    midhingeScorer(x = v5, i = i5), rep(3                   ,2))
  expect_equal(     trimeanScorer(x = v5, i = i5), rep(3.5                 ,2))
  expect_equal(         iqrScorer(x = v5, i = i5), rep(2                   ,2))
  expect_equal(         iqmScorer(x = v5, i = i5), rep(3.4                 ,2))
  expect_equal(         madScorer(x = v5, i = i5), rep(2.9652              ,2))
  expect_equal(         aadScorer(x = v5, i = i5), rep(2                   ,2))
  expect_equal(      ssgseaScorer(x = v5, i = i5), rep(getDefaultNaValue() ,2))
  expect_equal(        gsvaScorer(x = v5, i = i5), rep(getDefaultNaValue() ,2))
  expect_equal(       plageScorer(x = v5, i = i5), rep(getDefaultNaValue() ,2))
  expect_equal(      zscoreScorer(x = v5, i = i5), rep(getDefaultNaValue() ,2))
})


## Test 6-by-2 matrices ----------------------------------------------

test_that("Summary Scores functions works with 6-by-2 matrix of equal elements and signature with 6 matching elements", {
  expect_equal(         sumScorer(x = v6, i = i6), rep(48                  ,2))
  expect_equal( weightedSumScorer(x = v6, i = i6), rep(48                  ,2))
  expect_equal(        meanScorer(x = v6, i = i6), rep(8                   ,2))
  expect_equal( trimmedMeanScorer(x = v6, i = i6), rep(8                   ,2))
  expect_equal(weightedMeanScorer(x = v6, i = i6), rep(8                   ,2))
  expect_equal(      medianScorer(x = v6, i = i6), rep(8                   ,2))
  expect_equal(        modeScorer(x = v6, i = i6), rep(8                   ,2))
  expect_equal(    midrangeScorer(x = v6, i = i6), rep(8                   ,2))
  expect_equal(    midhingeScorer(x = v6, i = i6), rep(8                   ,2))
  expect_equal(     trimeanScorer(x = v6, i = i6), rep(8                   ,2))
  expect_equal(         iqrScorer(x = v6, i = i6), rep(0                   ,2))
  expect_equal(         iqmScorer(x = v6, i = i6), rep(8                   ,2))
  expect_equal(         madScorer(x = v6, i = i6), rep(0                   ,2))
  expect_equal(         aadScorer(x = v6, i = i6), rep(0                   ,2))
  expect_equal(      ssgseaScorer(x = v6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(        gsvaScorer(x = v6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(       plageScorer(x = v6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(      zscoreScorer(x = v6, i = i6), rep(getDefaultNaValue() ,2))
})

## Test matrices of zeros ----------------------------------------------

test_that("Summary Scores functions works with 2-by-2 matrix of zeros and signature with 2 matching elements", {
  expect_equal(         sumScorer(x = z2, i = i2), rep(0                   ,2))
  expect_equal( weightedSumScorer(x = z2, i = i2), rep(0                   ,2))
  expect_equal(        meanScorer(x = z2, i = i2), rep(0                   ,2))
  expect_equal( trimmedMeanScorer(x = z2, i = i2), rep(0                   ,2))
  expect_equal(weightedMeanScorer(x = z2, i = i2), rep(0                   ,2))
  expect_equal(      medianScorer(x = z2, i = i2), rep(0                   ,2))
  expect_equal(        modeScorer(x = z2, i = i2), rep(0                   ,2))
  expect_equal(    midrangeScorer(x = z2, i = i2), rep(0                   ,2))
  expect_equal(    midhingeScorer(x = z2, i = i2), rep(0                   ,2))
  expect_equal(     trimeanScorer(x = z2, i = i2), rep(0                   ,2))
  expect_equal(         iqrScorer(x = z2, i = i2), rep(0                   ,2))
  expect_equal(         iqmScorer(x = z2, i = i2), rep(getDefaultNaValue() ,2))
  expect_equal(         madScorer(x = z2, i = i2), rep(0                   ,2))
  expect_equal(         aadScorer(x = z2, i = i2), rep(0                   ,2))
  expect_equal(      ssgseaScorer(x = z2, i = i2), rep(getDefaultNaValue() ,2))
  expect_equal(        gsvaScorer(x = z2, i = i2), rep(getDefaultNaValue() ,2))
  expect_equal(       plageScorer(x = z2, i = i2), rep(getDefaultNaValue() ,2))
  expect_equal(      zscoreScorer(x = z2, i = i2), rep(getDefaultNaValue() ,2))
})

test_that("Summary Scores functions works with 6-by-2 matrix of zeros and signature with 6 matching elements", {
  expect_equal(         sumScorer(x = z6, i = i6), rep(0                   ,2))
  expect_equal( weightedSumScorer(x = z6, i = i6), rep(0                   ,2))
  expect_equal(        meanScorer(x = z6, i = i6), rep(0                   ,2))
  expect_equal( trimmedMeanScorer(x = z6, i = i6), rep(0                   ,2))
  expect_equal(weightedMeanScorer(x = z6, i = i6), rep(0                   ,2))
  expect_equal(      medianScorer(x = z6, i = i6), rep(0                   ,2))
  expect_equal(        modeScorer(x = z6, i = i6), rep(0                   ,2))
  expect_equal(    midrangeScorer(x = z6, i = i6), rep(0                   ,2))
  expect_equal(    midhingeScorer(x = z6, i = i6), rep(0                   ,2))
  expect_equal(     trimeanScorer(x = z6, i = i6), rep(0                   ,2))
  expect_equal(         iqrScorer(x = z6, i = i6), rep(0                   ,2))
  expect_equal(         iqmScorer(x = z6, i = i6), rep(0                   ,2))
  expect_equal(         madScorer(x = z6, i = i6), rep(0                   ,2))
  expect_equal(         aadScorer(x = z6, i = i6), rep(0                   ,2))
  expect_equal(      ssgseaScorer(x = z6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(        gsvaScorer(x = z6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(       plageScorer(x = z6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(      zscoreScorer(x = z6, i = i6), rep(getDefaultNaValue() ,2))
})

## Test matrices of NAs ----------------------------------------------

test_that("Summary Scores functions works with 6-by-2 matrix of NAs (`na.rm = TRUE`) and signature with 6 matching elements", {
  expect_equal(   computeColScores(score =          "sum", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =  "weightedSum", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =         "mean", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =  "trimmedMean", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score = "weightedMean", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =       "median", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =         "mode", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =     "midrange", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =     "midhinge", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =      "trimean", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =          "iqr", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =          "iqm", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =          "mad", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =          "aad", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =       "ssgsea", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =         "gsva", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =        "plage", x = na6, i = i6), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =       "zscore", x = na6, i = i6), rep(getDefaultNaValue() ,2))
})

test_that("Summary Scores functions works with 6-by-2 matrix of NAs (`na.rm = FALSE`) and signature with 6 matching elements", {
  expect_equal(   computeColScores(score =          "sum", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =  "weightedSum", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =         "mean", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =  "trimmedMean", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score = "weightedMean", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =       "median", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =         "mode", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =     "midrange", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =     "midhinge", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =      "trimean", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =          "iqr", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =          "iqm", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =          "mad", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =          "aad", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =       "ssgsea", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =         "gsva", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =        "plage", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
  expect_equal(   computeColScores(score =       "zscore", x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue() ,2))
})

## Test matrices with numbers and NAs ----------------------------------------------

test_that("Summary Scores functions works with 5-by-2 matrix containing 3 real numbers and 2 NAs (`na.rm = TRUE`) and signature with 5 matching elements", {
  expect_equal(         sumScorer(x = m5, i = i5, na.rm = TRUE), rep(9                  ,2))
  expect_equal( weightedSumScorer(x = m5, i = i5, na.rm = TRUE), rep(9                  ,2))
  expect_equal(        meanScorer(x = m5, i = i5, na.rm = TRUE), rep(3                  ,2))
  expect_equal( trimmedMeanScorer(x = m5, i = i5, na.rm = TRUE), rep(3                  ,2))
  expect_equal(weightedMeanScorer(x = m5, i = i5, na.rm = TRUE), rep(3                  ,2))
  expect_equal(      medianScorer(x = m5, i = i5, na.rm = TRUE), rep(2                  ,2))
  expect_equal(        modeScorer(x = m5, i = i5, na.rm = TRUE), rep(1                  ,2))
  expect_equal(    midrangeScorer(x = m5, i = i5, na.rm = TRUE), rep(3.5                ,2))
  expect_equal(    midhingeScorer(x = m5, i = i5, na.rm = TRUE), rep(2.75               ,2))
  expect_equal(     trimeanScorer(x = m5, i = i5, na.rm = TRUE), rep(2.375              ,2))
  expect_equal(         iqrScorer(x = m5, i = i5, na.rm = TRUE), rep(2.5                ,2))
  expect_equal(         iqmScorer(x = m5, i = i5, na.rm = TRUE), rep(getDefaultNaValue(),2))
  expect_equal(         madScorer(x = m5, i = i5, na.rm = TRUE), rep(1.4826             ,2))
  expect_equal(         aadScorer(x = m5, i = i5, na.rm = TRUE), rep(1.66666667         ,2))
  expect_equal(      ssgseaScorer(x = m5, i = i5, na.rm = TRUE), rep(getDefaultNaValue(),2))
  expect_equal(        gsvaScorer(x = m5, i = i5, na.rm = TRUE), rep(getDefaultNaValue(),2))
  expect_equal(       plageScorer(x = m5, i = i5, na.rm = TRUE), rep(getDefaultNaValue(),2))
  expect_equal(      zscoreScorer(x = m5, i = i5, na.rm = TRUE), rep(getDefaultNaValue(),2))
})

test_that("Summary Scores functions works with 5-by-2 matrix containing 3 real numbers and 2 NAs (`na.rm = FALSE`) and signature with 5 matching elements", {
  expect_equal(         sumScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal( weightedSumScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(        meanScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal( trimmedMeanScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(weightedMeanScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(      medianScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(        modeScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(    midrangeScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(    midhingeScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(     trimeanScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(         iqrScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(         iqmScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(         madScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(         aadScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(      ssgseaScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(        gsvaScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(       plageScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(      zscoreScorer(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
})

test_that("Summary Scores functions works with 6-by-2 matrix containing 3 real numbers and 2 NAs (`na.rm = TRUE`) and signature with 6 matching elements", {
  expect_equal(         sumScorer(x = m6, i = i6, na.rm = TRUE), c(13,  14))
  expect_equal( weightedSumScorer(x = m6, i = i6, na.rm = TRUE), c(13,  14))
  expect_equal(        meanScorer(x = m6, i = i6, na.rm = TRUE), c(2.6,2.8))
  expect_equal( trimmedMeanScorer(x = m6, i = i6, na.rm = TRUE), c(2.6,2.8))
  expect_equal(weightedMeanScorer(x = m6, i = i6, na.rm = TRUE), c(2.6,2.8))
  expect_equal(      medianScorer(x = m6, i = i6, na.rm = TRUE), c(2  ,  2))
  expect_equal(        modeScorer(x = m6, i = i6, na.rm = TRUE), c(1  ,  1))
  expect_equal(    midrangeScorer(x = m6, i = i6, na.rm = TRUE), c(3.5,3.5))
  expect_equal(    midhingeScorer(x = m6, i = i6, na.rm = TRUE), c(2.0,2.5))
  expect_equal(     trimeanScorer(x = m6, i = i6, na.rm = TRUE), c(2.0,2.25))
  expect_equal(         iqrScorer(x = m6, i = i6, na.rm = TRUE), c(2,3))
  expect_equal(         iqmScorer(x = m6, i = i6, na.rm = TRUE), c(2,2.3))
  expect_equal(         madScorer(x = m6, i = i6, na.rm = TRUE), c(1.4826, 1.4826))
  expect_equal(         aadScorer(x = m6, i = i6, na.rm = TRUE), c(1.4,1.6))
  expect_equal(      ssgseaScorer(x = m6, i = i6, na.rm = TRUE), c(0.31042006, 1.31042006))
  expect_equal(        gsvaScorer(x = m6, i = i6, na.rm = TRUE), c(1,1))
  expect_equal(       plageScorer(x = m6, i = i6, na.rm = TRUE), c(-0.70710678, 0.70710678))
  expect_equal(      zscoreScorer(x = m6, i = i6, na.rm = TRUE), rep(0,2))
})

test_that("Summary Scores functions works with 6-by-2 matrix containing 3 real numbers and 2 NAs (`na.rm = FALSE`) and signature with 6 matching elements", {
  expect_equal(         sumScorer(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal( weightedSumScorer(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(        meanScorer(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal( trimmedMeanScorer(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(weightedMeanScorer(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(      medianScorer(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(        modeScorer(x = m6, i = i6, na.rm = FALSE), rep(1,                  2))
  expect_equal(    midrangeScorer(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(    midhingeScorer(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(     trimeanScorer(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(         iqrScorer(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(         iqmScorer(x = m6, i = i6, na.rm = FALSE), c(2.0,2.3))
  expect_equal(         madScorer(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(         aadScorer(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(      ssgseaScorer(x = m6, i = i6, na.rm = FALSE), c(NaN, NaN))
  expect_equal(        gsvaScorer(x = m6, i = i6, na.rm = FALSE), c(1,1))
  expect_equal(       plageScorer(x = m6, i = i6, na.rm = FALSE), c(-0.70710678, 0.70710678))
  expect_equal(      zscoreScorer(x = m6, i = i6, na.rm = FALSE), rep(0,2))
})
