#'@include utility-functions.R
NULL

library(usethis)
library(testthat)



# Test 1-column matrices ----------------------------------------------

#matrix of numbers
v1 = c(1)
v2 = c(1,4)
v3 = c(2,6,1)
v4 = c(3,5,1,3)
v5 = c(1,4,4,2,9)
v6 = c(8,8,8,8,8,8)
v7 = c(1,1,4,4,3,2,1)
v8 = c(1,1,4,4,3,2,1,7)
v1 = matrix(v1, ncol = 1)
v2 = matrix(v2, ncol = 1)
v3 = matrix(v3, ncol = 1)
v4 = matrix(v4, ncol = 1)
v5 = matrix(v5, ncol = 1)
v6 = matrix(v6, ncol = 1)
v7 = matrix(v7, ncol = 1)
v8 = matrix(v8, ncol = 1)


#zeros
z1 = 0
z2 = c(0,0)
z6 = c(0,0,0,0,0,0)
z1 = matrix(z1, ncol = 1)
z2 = matrix(z2, ncol = 1)
z6 = matrix(z6, ncol = 1)


#NAs
na1 = NA
na2 = c(NA,NA)
na6 = c(NA,NA,NA,NA,NA,NA)
na1 = matrix(na1, ncol = 1)
na2 = matrix(na2, ncol = 1)
na6 = matrix(na6, ncol = 1)

#numbers and NAs
m2 = c(2, NA)
m3 = c(2, NA, 4)
m4 = c(2, NA, 3, 4)
m5 = c(2, 6, NA, NA, 1)
m2 = matrix(m2, ncol = 1)
m3 = matrix(m3, ncol = 1)
m4 = matrix(m4, ncol = 1)
m5 = matrix(m5, ncol = 1)

#gene signatures
i1 = 1
i2 = c(1,2)
i3 = seq_len(length.out = 3)
i4 = seq_len(length.out = 4)
i5 = seq_len(length.out = 5)
i6 = seq_len(length.out = 6)
i1r = c(1, sample(x = seq_len(100), size = 19))
iwom = 20

## Test 1-by-1 matrices ----------------------------------------------

test_that("Summary Scores functions works with 1-by-1 matrix and signature with 1 matching element", {
  expect_equal(             meanScores(x = v1, i = i1), 1)
  expect_equal(      trimmedMeanScores(x = v1, i = i1), 1)
  expect_equal(     weightedMeanScores(x = v1, i = i1), 1)
  expect_equal(           medianScores(x = v1, i = i1), 1)
  expect_equal(             modeScores(x = v1, i = i1), 1)
  expect_equal(         midrangeScores(x = v1, i = i1), 1)
  expect_equal(         midhingeScores(x = v1, i = i1), 1)
  expect_equal(          trimeanScores(x = v1, i = i1), 1)
  expect_equal(          briskowScores(x = v1, i = i1), 0)
  expect_equal(  reviewedBriskowScores(x = v1, i = i1), 0)
  expect_equal(interquartileMeanScores(x = v1, i = i1), getDefaultNaValue())
  expect_equal(      weightedSumScores(x = v1, i = i1), 1)
  expect_equal(           ssGseaScores(x = v1, i = i1), getDefaultNaValue())
  expect_equal(             gsvaScores(x = v1, i = i1), getDefaultNaValue())
  expect_equal(            plageScores(x = v1, i = i1), getDefaultNaValue())
  expect_equal(                zScores(x = v1, i = i1), getDefaultNaValue())
})

test_that("Summary Scores functions works with 1-by-1 matrix and signature with 2 matching elements", {
  expect_equal(             meanScores(x = v1, i = i2), 1)
  expect_equal(      trimmedMeanScores(x = v1, i = i2), 1)
  expect_equal(     weightedMeanScores(x = v1, i = i2), 1)
  expect_equal(           medianScores(x = v1, i = i2), 1)
  expect_equal(             modeScores(x = v1, i = i2), 1)
  expect_equal(         midrangeScores(x = v1, i = i2), 1)
  expect_equal(         midhingeScores(x = v1, i = i2), 1)
  expect_equal(          trimeanScores(x = v1, i = i2), 1)
  expect_equal(          briskowScores(x = v1, i = i2), 0)
  expect_equal(  reviewedBriskowScores(x = v1, i = i2), 0)
  expect_equal(interquartileMeanScores(x = v1, i = i2), getDefaultNaValue())
  expect_equal(      weightedSumScores(x = v1, i = i2), 1)
  expect_equal(           ssGseaScores(x = v1, i = i2), getDefaultNaValue())
  expect_equal(             gsvaScores(x = v1, i = i2), getDefaultNaValue())
  expect_equal(            plageScores(x = v1, i = i2), getDefaultNaValue())
  expect_equal(                zScores(x = v1, i = i2), getDefaultNaValue())
})

test_that("Summary Scores functions works with 1-by-1 matrix and signature with 20 elements (1 matching)", {
  expect_equal(             meanScores(x = v1, i = i1r), 1)
  expect_equal(      trimmedMeanScores(x = v1, i = i1r), 1)
  expect_equal(     weightedMeanScores(x = v1, i = i1r), 1)
  expect_equal(           medianScores(x = v1, i = i1r), 1)
  expect_equal(             modeScores(x = v1, i = i1r), 1)
  expect_equal(         midrangeScores(x = v1, i = i1r), 1)
  expect_equal(         midhingeScores(x = v1, i = i1r), 1)
  expect_equal(          trimeanScores(x = v1, i = i1r), 1)
  expect_equal(          briskowScores(x = v1, i = i1r), 0)
  expect_equal(  reviewedBriskowScores(x = v1, i = i1r), 0)
  expect_equal(interquartileMeanScores(x = v1, i = i1r), getDefaultNaValue())
  expect_equal(      weightedSumScores(x = v1, i = i1r), 1)
  expect_equal(           ssGseaScores(x = v1, i = i1r), getDefaultNaValue())
  expect_equal(             gsvaScores(x = v1, i = i1r), getDefaultNaValue())
  expect_equal(            plageScores(x = v1, i = i1r), getDefaultNaValue())
  expect_equal(                zScores(x = v1, i = i1r), getDefaultNaValue())
})

test_that("Summary Scores functions works with 1-by-1 matrix and signature without matching elements", {
  expect_equal(             meanScores(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(      trimmedMeanScores(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(     weightedMeanScores(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(           medianScores(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(             modeScores(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(         midrangeScores(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(         midhingeScores(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(          trimeanScores(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(          briskowScores(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(  reviewedBriskowScores(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(interquartileMeanScores(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(      weightedSumScores(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(           ssGseaScores(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(             gsvaScores(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(            plageScores(x = v1, i = iwom), getDefaultNaValue())
  expect_equal(                zScores(x = v1, i = iwom), getDefaultNaValue())
})

## Test 2-by-1 matrices ----------------------------------------------

test_that("Summary Scores functions works with 2-by-1 matrix and signature with 1 matching element", {
  expect_equal(             meanScores(x = v2, i = i1), 1)
  expect_equal(      trimmedMeanScores(x = v2, i = i1), 1)
  expect_equal(     weightedMeanScores(x = v2, i = i1), 1)
  expect_equal(           medianScores(x = v2, i = i1), 1)
  expect_equal(             modeScores(x = v2, i = i1), 1)
  expect_equal(         midrangeScores(x = v2, i = i1), 1)
  expect_equal(         midhingeScores(x = v2, i = i1), 1)
  expect_equal(          trimeanScores(x = v2, i = i1), 1)
  expect_equal(          briskowScores(x = v2, i = i1), 0)
  expect_equal(  reviewedBriskowScores(x = v2, i = i1), 0)
  expect_equal(interquartileMeanScores(x = v2, i = i1), getDefaultNaValue())
  expect_equal(      weightedSumScores(x = v2, i = i1), 1)
  expect_equal(           ssGseaScores(x = v2, i = i1), getDefaultNaValue())
  expect_equal(             gsvaScores(x = v2, i = i1), getDefaultNaValue())
  expect_equal(            plageScores(x = v2, i = i1), getDefaultNaValue())
  expect_equal(                zScores(x = v2, i = i1), getDefaultNaValue())
})


test_that("Summary Scores functions works with 2-by-1 matrix and signature with 2 matching elements", {
  expect_equal(             meanScores(x = v2, i = i2), 2.5)
  expect_equal(      trimmedMeanScores(x = v2, i = i2), 2.5)
  expect_equal(     weightedMeanScores(x = v2, i = i2), 2.5)
  expect_equal(           medianScores(x = v2, i = i2), 2.5)
  expect_equal(             modeScores(x = v2, i = i2), 1)
  expect_equal(         midrangeScores(x = v2, i = i2), 2.5)
  expect_equal(         midhingeScores(x = v2, i = i2), 2.5)
  expect_equal(          trimeanScores(x = v2, i = i2), 2.5)
  expect_equal(          briskowScores(x = v2, i = i2), 0)
  expect_equal(  reviewedBriskowScores(x = v2, i = i2), 0)
  expect_equal(interquartileMeanScores(x = v2, i = i2), getDefaultNaValue())
  expect_equal(      weightedSumScores(x = v2, i = i2), 5)
  expect_equal(           ssGseaScores(x = v2, i = i2), getDefaultNaValue())
  expect_equal(             gsvaScores(x = v2, i = i2), getDefaultNaValue())
  expect_equal(            plageScores(x = v2, i = i2), getDefaultNaValue())
  expect_equal(                zScores(x = v2, i = i2), getDefaultNaValue())
})

## Test 3-by-1 matrices ----------------------------------------------

test_that("Summary Scores functions works with 3-by-1 matrix and signature with 3 matching elements", {
  expect_equal(             meanScores(x = v3, i = i3), 3)
  expect_equal(      trimmedMeanScores(x = v3, i = i3), 3)
  expect_equal(     weightedMeanScores(x = v3, i = i3), 3)
  expect_equal(           medianScores(x = v3, i = i3), 2)
  expect_equal(             modeScores(x = v3, i = i3), 1)
  expect_equal(         midrangeScores(x = v3, i = i3), 3.5)
  expect_equal(         midhingeScores(x = v3, i = i3), 2.75)
  expect_equal(          trimeanScores(x = v3, i = i3), 2.375)
  expect_equal(          briskowScores(x = v3, i = i3), 0)
  expect_equal(  reviewedBriskowScores(x = v3, i = i3), 0)
  expect_equal(interquartileMeanScores(x = v3, i = i3), getDefaultNaValue())
  expect_equal(      weightedSumScores(x = v3, i = i3), 9)
  expect_equal(           ssGseaScores(x = v3, i = i3), getDefaultNaValue())
  expect_equal(             gsvaScores(x = v3, i = i3), getDefaultNaValue())
  expect_equal(            plageScores(x = v3, i = i3), getDefaultNaValue())
  expect_equal(                zScores(x = v3, i = i3), getDefaultNaValue())
})

## Test 4-by-1 matrices ----------------------------------------------

test_that("Summary Scores functions works with 4-by-1 matrix and signature with 4 matching elements", {
  expect_equal(             meanScores(x = v4, i = i4), 3)
  expect_equal(      trimmedMeanScores(x = v4, i = i4), 3)
  expect_equal(     weightedMeanScores(x = v4, i = i4), 3)
  expect_equal(           medianScores(x = v4, i = i4), 3)
  expect_equal(             modeScores(x = v4, i = i4), 3)
  expect_equal(         midrangeScores(x = v4, i = i4), 3)
  expect_equal(         midhingeScores(x = v4, i = i4), 3)
  expect_equal(          trimeanScores(x = v4, i = i4), 3)
  expect_equal(          briskowScores(x = v4, i = i4), 0)
  expect_equal(  reviewedBriskowScores(x = v4, i = i4), 0)
  expect_equal(interquartileMeanScores(x = v4, i = i4), 3)
  expect_equal(      weightedSumScores(x = v4, i = i4), 12)
  expect_equal(           ssGseaScores(x = v4, i = i4), getDefaultNaValue())
  expect_equal(             gsvaScores(x = v4, i = i4), getDefaultNaValue())
  expect_equal(            plageScores(x = v4, i = i4), getDefaultNaValue())
  expect_equal(                zScores(x = v4, i = i4), getDefaultNaValue())
})

## Test 5-by-1 matrices ----------------------------------------------

test_that("Summary Scores functions works with 5-by-1 matrix and signature with 5 matching elements", {
  expect_equal(             meanScores(x = v5, i = i5), 4)
  expect_equal(      trimmedMeanScores(x = v5, i = i5), 4)
  expect_equal(     weightedMeanScores(x = v5, i = i5), 4)
  expect_equal(           medianScores(x = v5, i = i5), 4)
  expect_equal(             modeScores(x = v5, i = i5), 4)
  expect_equal(         midrangeScores(x = v5, i = i5), 5)
  expect_equal(         midhingeScores(x = v5, i = i5), 3)
  expect_equal(          trimeanScores(x = v5, i = i5), 3.5)
  expect_equal(          briskowScores(x = v5, i = i5), -1)
  expect_equal(  reviewedBriskowScores(x = v5, i = i5), -0.2)
  expect_equal(interquartileMeanScores(x = v5, i = i5), 3.4)
  expect_equal(      weightedSumScores(x = v5, i = i5), 20)
  expect_equal(           ssGseaScores(x = v5, i = i5), getDefaultNaValue())
  expect_equal(             gsvaScores(x = v5, i = i5), getDefaultNaValue())
  expect_equal(            plageScores(x = v5, i = i5), getDefaultNaValue())
  expect_equal(                zScores(x = v5, i = i5), getDefaultNaValue())
})


## Test 6-by-1 matrices ----------------------------------------------

test_that("Summary Scores functions works with 6-by-1 matrix of equal elements and signature with 6 matching elements", {
  expect_equal(             meanScores(x = v6, i = i6), 8)
  expect_equal(      trimmedMeanScores(x = v6, i = i6), 8)
  expect_equal(     weightedMeanScores(x = v6, i = i6), 8)
  expect_equal(           medianScores(x = v6, i = i6), 8)
  expect_equal(             modeScores(x = v6, i = i6), 8)
  expect_equal(         midrangeScores(x = v6, i = i6), 8)
  expect_equal(         midhingeScores(x = v6, i = i6), 8)
  expect_equal(          trimeanScores(x = v6, i = i6), 8)
  expect_equal(          briskowScores(x = v6, i = i6), 0)
  expect_equal(  reviewedBriskowScores(x = v6, i = i6), 0)
  expect_equal(interquartileMeanScores(x = v6, i = i6), 8)
  expect_equal(      weightedSumScores(x = v6, i = i6), 48)
  expect_equal(           ssGseaScores(x = v6, i = i6), getDefaultNaValue())
  expect_equal(             gsvaScores(x = v6, i = i6), getDefaultNaValue())
  expect_equal(            plageScores(x = v6, i = i6), getDefaultNaValue())
  expect_equal(                zScores(x = v6, i = i6), getDefaultNaValue())
})


## Test matrices of zeros ----------------------------------------------

test_that("Summary Scores functions works with 2-by-1 matrix of zeros and signature with 2 matching elements", {
  expect_equal(             meanScores(x = z2, i = i2), 0)
  expect_equal(      trimmedMeanScores(x = z2, i = i2), 0)
  expect_equal(     weightedMeanScores(x = z2, i = i2), 0)
  expect_equal(           medianScores(x = z2, i = i2), 0)
  expect_equal(             modeScores(x = z2, i = i2), 0)
  expect_equal(         midrangeScores(x = z2, i = i2), 0)
  expect_equal(         midhingeScores(x = z2, i = i2), 0)
  expect_equal(          trimeanScores(x = z2, i = i2), 0)
  expect_equal(          briskowScores(x = z2, i = i2), 0)
  expect_equal(  reviewedBriskowScores(x = z2, i = i2), 0)
  expect_equal(interquartileMeanScores(x = z2, i = i2), getDefaultNaValue())
  expect_equal(      weightedSumScores(x = z2, i = i2), 0)
  expect_equal(           ssGseaScores(x = z2, i = i2), getDefaultNaValue())
  expect_equal(             gsvaScores(x = z2, i = i2), getDefaultNaValue())
  expect_equal(            plageScores(x = z2, i = i2), getDefaultNaValue())
  expect_equal(                zScores(x = z2, i = i2), getDefaultNaValue())
})

test_that("Summary Scores functions works with 6-by-1 matrix of zeros and signature with 6 matching elements", {
  expect_equal(             meanScores(x = z6, i = i6), 0)
  expect_equal(      trimmedMeanScores(x = z6, i = i6), 0)
  expect_equal(     weightedMeanScores(x = z6, i = i6), 0)
  expect_equal(           medianScores(x = z6, i = i6), 0)
  expect_equal(             modeScores(x = z6, i = i6), 0)
  expect_equal(         midrangeScores(x = z6, i = i6), 0)
  expect_equal(         midhingeScores(x = z6, i = i6), 0)
  expect_equal(          trimeanScores(x = z6, i = i6), 0)
  expect_equal(          briskowScores(x = z6, i = i6), 0)
  expect_equal(  reviewedBriskowScores(x = z6, i = i6), 0)
  expect_equal(interquartileMeanScores(x = z6, i = i6), 0)
  expect_equal(      weightedSumScores(x = z6, i = i6), 0)
  expect_equal(           ssGseaScores(x = z6, i = i6), getDefaultNaValue())
  expect_equal(             gsvaScores(x = z6, i = i6), getDefaultNaValue())
  expect_equal(            plageScores(x = z6, i = i6), getDefaultNaValue())
  expect_equal(                zScores(x = z6, i = i6), getDefaultNaValue())
})

## Test matrices of NAs ----------------------------------------------

test_that("Summary Scores functions works with 6-by-1 matrix of NAs (`na.rm = TRUE`) and signature with 6 matching elements", {
  expect_equal(             meanScores(x = na6, i = i6), getDefaultNaValue())
  expect_equal(      trimmedMeanScores(x = na6, i = i6), getDefaultNaValue())
  expect_equal(     weightedMeanScores(x = na6, i = i6), getDefaultNaValue())
  expect_equal(           medianScores(x = na6, i = i6), getDefaultNaValue())
  expect_equal(             modeScores(x = na6, i = i6), getDefaultNaValue())
  expect_equal(         midrangeScores(x = na6, i = i6), getDefaultNaValue())
  expect_equal(         midhingeScores(x = na6, i = i6), getDefaultNaValue())
  expect_equal(          trimeanScores(x = na6, i = i6), getDefaultNaValue())
  expect_equal(          briskowScores(x = na6, i = i6), getDefaultNaValue())
  expect_equal(  reviewedBriskowScores(x = na6, i = i6), getDefaultNaValue())
  expect_equal(interquartileMeanScores(x = na6, i = i6), getDefaultNaValue())
  expect_equal(      weightedSumScores(x = na6, i = i6), getDefaultNaValue())
  expect_equal(           ssGseaScores(x = na6, i = i6), getDefaultNaValue())
  expect_equal(             gsvaScores(x = na6, i = i6), getDefaultNaValue())
  expect_equal(            plageScores(x = na6, i = i6), getDefaultNaValue())
  expect_equal(                zScores(x = na6, i = i6), getDefaultNaValue())

})

test_that("Summary Scores functions works with 6-by-1 matrix of NAs (`na.rm = FALSE`) and signature with 6 matching elements", {
  expect_equal(             meanScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(      trimmedMeanScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(     weightedMeanScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(           medianScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(             modeScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(         midrangeScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(         midhingeScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(          trimeanScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(          briskowScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(  reviewedBriskowScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(interquartileMeanScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(      weightedSumScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(           ssGseaScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(             gsvaScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(            plageScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(                zScores(x = na6, i = i6, na.rm = FALSE), getDefaultNaValue())
})

## Test matrices with numbers and NAs ----------------------------------------------

test_that("Summary Scores functions works with 5-by-1 matrix containing 3 real numbers and 2 NAs (`na.rm = TRUE`) and signature with 5 matching elements", {
  expect_equal(             meanScores(x = m5, i = i5, na.rm = TRUE), 3)
  expect_equal(      trimmedMeanScores(x = m5, i = i5, na.rm = TRUE), 3)
  expect_equal(     weightedMeanScores(x = m5, i = i5, na.rm = TRUE), 3)
  expect_equal(           medianScores(x = m5, i = i5, na.rm = TRUE), 2)
  expect_equal(             modeScores(x = m5, i = i5, na.rm = TRUE), 1)
  expect_equal(         midrangeScores(x = m5, i = i5, na.rm = TRUE), 3.5)
  expect_equal(         midhingeScores(x = m5, i = i5, na.rm = TRUE), 2.75)
  expect_equal(          trimeanScores(x = m5, i = i5, na.rm = TRUE), 2.375)
  expect_equal(          briskowScores(x = m5, i = i5, na.rm = TRUE), 0)
  expect_equal(  reviewedBriskowScores(x = m5, i = i5, na.rm = TRUE), 0)
  expect_equal(interquartileMeanScores(x = m5, i = i5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(      weightedSumScores(x = m5, i = i5, na.rm = TRUE), 9)
  expect_equal(           ssGseaScores(x = m5, i = i5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(             gsvaScores(x = m5, i = i5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(            plageScores(x = m5, i = i5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(                zScores(x = m5, i = i5, na.rm = TRUE), getDefaultNaValue())
})

test_that("Summary Scores functions works with 5-by-1 matrix containing 3 real numbers and 2 NAs (`na.rm = FALSE`) and signature with 5 matching elements", {
  expect_equal(             meanScores(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(      trimmedMeanScores(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(     weightedMeanScores(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(           medianScores(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(             modeScores(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(         midrangeScores(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(         midhingeScores(x = m5, i = i5, na.rm = FALSE), 2.75)
  expect_equal(          trimeanScores(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(          briskowScores(x = m5, i = i5, na.rm = FALSE), 0)
  expect_equal(  reviewedBriskowScores(x = m5, i = i5, na.rm = FALSE), 0)
  expect_equal(interquartileMeanScores(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(      weightedSumScores(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(           ssGseaScores(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(             gsvaScores(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(            plageScores(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(                zScores(x = m5, i = i5, na.rm = FALSE), getDefaultNaValue())
})



# Test 2-column matrices ----------------------------------------------

#matrix of numbers
v1 = c(1)
v2 = c(1,4)
v3 = c(2,6,1)
v4 = c(3,5,1,3)
v5 = c(1,4,4,2,9)
v6 = c(8,8,8,8,8,8)
v7 = c(1,1,4,4,3,2,1)
v8 = c(1,1,4,4,3,2,1,7)
v1 = matrix(c(v1, v1), ncol = 2)
v2 = matrix(c(v2, v2), ncol = 2)
v3 = matrix(c(v3, v3), ncol = 2)
v4 = matrix(c(v4, v4), ncol = 2)
v5 = matrix(c(v5, v5), ncol = 2)
v6 = matrix(c(v6, v6), ncol = 2)
v7 = matrix(c(v7, v7), ncol = 2)
v8 = matrix(c(v8, v8), ncol = 2)


#zeros
z1 = 0
z2 = c(0,0)
z6 = c(0,0,0,0,0,0)
z1 = matrix(c(z1, z1), ncol = 2)
z2 = matrix(c(z2, z2), ncol = 2)
z6 = matrix(c(z6, z6), ncol = 2)


#NAs
na1 = NA
na2 = c(NA,NA)
na6 = c(NA,NA,NA,NA,NA,NA)
na1 = matrix(c(na1, na1), ncol = 2)
na2 = matrix(c(na2, na2), ncol = 2)
na6 = matrix(c(na6, na6), ncol = 2)

#numbers and NAs
m2 = c(2, NA)
m3 = c(2, NA, 4)
m4 = c(2, NA, 3, 4)
m5 = c(2, 6, NA, NA, 1)
m6a= c(6, 1, 1, NA, 3, 2)
m6b= c(2, 6,NA,  1, 4, 1)
m2 = matrix(c(m2, m2), ncol = 2)
m3 = matrix(c(m3, m3), ncol = 2)
m4 = matrix(c(m4, m4), ncol = 2)
m5 = matrix(c(m5, m5), ncol = 2)
m6 = matrix(c(m6a, m6b), ncol = 2)

#gene signatures
i1 = 1
i2 = c(1,2)
i3 = seq_len(length.out = 3)
i4 = seq_len(length.out = 4)
i5 = seq_len(length.out = 5)
i6 = seq_len(length.out = 6)
i1r = c(1, sample(x = seq_len(100), size = 19))
iwom = 20


## Test 1-by-2 matrices ----------------------------------------------

test_that("Summary Scores functions works with 1-by-2 matrix and signature with 1 matching element", {
  expect_equal(             meanScores(x = v1, i = i1), rep(1, 2))
  expect_equal(      trimmedMeanScores(x = v1, i = i1), rep(1, 2))
  expect_equal(     weightedMeanScores(x = v1, i = i1), rep(1, 2))
  expect_equal(           medianScores(x = v1, i = i1), rep(1, 2))
  expect_equal(             modeScores(x = v1, i = i1), rep(1, 2))
  expect_equal(         midrangeScores(x = v1, i = i1), rep(1, 2))
  expect_equal(         midhingeScores(x = v1, i = i1), rep(1, 2))
  expect_equal(          trimeanScores(x = v1, i = i1), rep(1, 2))
  expect_equal(          briskowScores(x = v1, i = i1), rep(0, 2))
  expect_equal(  reviewedBriskowScores(x = v1, i = i1), rep(0, 2))
  expect_equal(interquartileMeanScores(x = v1, i = i1), rep(getDefaultNaValue(), 2))
  expect_equal(      weightedSumScores(x = v1, i = i1), rep(1, 2))
  expect_equal(           ssGseaScores(x = v1, i = i1), rep(getDefaultNaValue(), 2))
  expect_equal(             gsvaScores(x = v1, i = i1), rep(getDefaultNaValue(), 2))
  expect_equal(            plageScores(x = v1, i = i1), rep(getDefaultNaValue(), 2))
  expect_equal(                zScores(x = v1, i = i1), rep(getDefaultNaValue(), 2))
})

test_that("Summary Scores functions works with 1-by-2 matrix and signature with 2 matching elements", {
  expect_equal(             meanScores(x = v1, i = i2), rep(1,2))
  expect_equal(      trimmedMeanScores(x = v1, i = i2), rep(1,2))
  expect_equal(     weightedMeanScores(x = v1, i = i2), rep(1,2))
  expect_equal(           medianScores(x = v1, i = i2), rep(1,2))
  expect_equal(             modeScores(x = v1, i = i2), rep(1,2))
  expect_equal(         midrangeScores(x = v1, i = i2), rep(1,2))
  expect_equal(         midhingeScores(x = v1, i = i2), rep(1,2))
  expect_equal(          trimeanScores(x = v1, i = i2), rep(1,2))
  expect_equal(          briskowScores(x = v1, i = i2), rep(0,2))
  expect_equal(  reviewedBriskowScores(x = v1, i = i2), rep(0,2))
  expect_equal(interquartileMeanScores(x = v1, i = i2), rep(getDefaultNaValue(),2))
  expect_equal(      weightedSumScores(x = v1, i = i2), rep(1,2))
  expect_equal(           ssGseaScores(x = v1, i = i2), rep(getDefaultNaValue(),2))
  expect_equal(             gsvaScores(x = v1, i = i2), rep(getDefaultNaValue(),2))
  expect_equal(            plageScores(x = v1, i = i2), rep(getDefaultNaValue(),2))
  expect_equal(                zScores(x = v1, i = i2), rep(getDefaultNaValue(),2))
})

test_that("Summary Scores functions works with 1-by-2 matrix and signature with 20 elements (1 matching)", {
  expect_equal(             meanScores(x = v1, i = i1r), rep(1,2))
  expect_equal(      trimmedMeanScores(x = v1, i = i1r), rep(1,2))
  expect_equal(     weightedMeanScores(x = v1, i = i1r), rep(1,2))
  expect_equal(           medianScores(x = v1, i = i1r), rep(1,2))
  expect_equal(             modeScores(x = v1, i = i1r), rep(1,2))
  expect_equal(         midrangeScores(x = v1, i = i1r), rep(1,2))
  expect_equal(         midhingeScores(x = v1, i = i1r), rep(1,2))
  expect_equal(          trimeanScores(x = v1, i = i1r), rep(1,2))
  expect_equal(          briskowScores(x = v1, i = i1r), rep(0,2))
  expect_equal(  reviewedBriskowScores(x = v1, i = i1r), rep(0,2))
  expect_equal(interquartileMeanScores(x = v1, i = i1r), rep(getDefaultNaValue(),2))
  expect_equal(      weightedSumScores(x = v1, i = i1r), rep(1,2))
  expect_equal(           ssGseaScores(x = v1, i = i1r), rep(getDefaultNaValue(),2))
  expect_equal(             gsvaScores(x = v1, i = i1r), rep(getDefaultNaValue(),2))
  expect_equal(            plageScores(x = v1, i = i1r), rep(getDefaultNaValue(),2))
  expect_equal(                zScores(x = v1, i = i1r), rep(getDefaultNaValue(),2))
})

test_that("Summary Scores functions works with 1-by-2 matrix and signature without matching elements", {
  expect_equal(             meanScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
  expect_equal(      trimmedMeanScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
  expect_equal(     weightedMeanScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
  expect_equal(           medianScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
  expect_equal(             modeScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
  expect_equal(         midrangeScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
  expect_equal(         midhingeScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
  expect_equal(          trimeanScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
  expect_equal(          briskowScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
  expect_equal(  reviewedBriskowScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
  expect_equal(interquartileMeanScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
  expect_equal(      weightedSumScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
  expect_equal(           ssGseaScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
  expect_equal(             gsvaScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
  expect_equal(            plageScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
  expect_equal(                zScores(x = v1, i = iwom), rep(getDefaultNaValue(),2))
})

## Test 2-by-2 matrices ----------------------------------------------

test_that("Summary Scores functions works with 2-by-2 matrix and signature with 1 matching element", {
  expect_equal(             meanScores(x = v2, i = i1), rep(1,2))
  expect_equal(      trimmedMeanScores(x = v2, i = i1), rep(1,2))
  expect_equal(     weightedMeanScores(x = v2, i = i1), rep(1,2))
  expect_equal(           medianScores(x = v2, i = i1), rep(1,2))
  expect_equal(             modeScores(x = v2, i = i1), rep(1,2))
  expect_equal(         midrangeScores(x = v2, i = i1), rep(1,2))
  expect_equal(         midhingeScores(x = v2, i = i1), rep(1,2))
  expect_equal(          trimeanScores(x = v2, i = i1), rep(1,2))
  expect_equal(          briskowScores(x = v2, i = i1), rep(0,2))
  expect_equal(  reviewedBriskowScores(x = v2, i = i1), rep(0,2))
  expect_equal(interquartileMeanScores(x = v2, i = i1), rep(getDefaultNaValue(),2))
  expect_equal(      weightedSumScores(x = v2, i = i1), rep(1,2))
  expect_equal(           ssGseaScores(x = v2, i = i1), rep(getDefaultNaValue(),2))
  expect_equal(             gsvaScores(x = v2, i = i1), rep(getDefaultNaValue(),2))
  expect_equal(            plageScores(x = v2, i = i1), rep(getDefaultNaValue(),2))
  expect_equal(                zScores(x = v2, i = i1), rep(getDefaultNaValue(),2))
})


test_that("Summary Scores functions works with 2-by-2 matrix and signature with 2 matching elements", {
  expect_equal(             meanScores(x = v2, i = i2), rep(2.5,2))
  expect_equal(      trimmedMeanScores(x = v2, i = i2), rep(2.5,2))
  expect_equal(     weightedMeanScores(x = v2, i = i2), rep(2.5,2))
  expect_equal(           medianScores(x = v2, i = i2), rep(2.5,2))
  expect_equal(             modeScores(x = v2, i = i2), rep(1  ,2))
  expect_equal(         midrangeScores(x = v2, i = i2), rep(2.5,2))
  expect_equal(         midhingeScores(x = v2, i = i2), rep(2.5,2))
  expect_equal(          trimeanScores(x = v2, i = i2), rep(2.5,2))
  expect_equal(          briskowScores(x = v2, i = i2), rep(0  ,2))
  expect_equal(  reviewedBriskowScores(x = v2, i = i2), rep(0  ,2))
  expect_equal(      weightedSumScores(x = v2, i = i2), rep(5  ,2))
  expect_equal(interquartileMeanScores(x = v2, i = i2), rep(getDefaultNaValue(),2))
  expect_equal(           ssGseaScores(x = v2, i = i2), rep(getDefaultNaValue(),2))
  expect_equal(             gsvaScores(x = v2, i = i2), rep(getDefaultNaValue(),2))
  expect_equal(            plageScores(x = v2, i = i2), rep(getDefaultNaValue(),2))
  expect_equal(                zScores(x = v2, i = i2), rep(getDefaultNaValue(),2))
})

## Test 3-by-1 matrices ----------------------------------------------
test_that("Summary Scores functions works with 3-by-2 matrix and signature with 3 matching elements", {
  expect_equal(             meanScores(x = v3, i = i3), rep(3    ,2))
  expect_equal(      trimmedMeanScores(x = v3, i = i3), rep(3    ,2))
  expect_equal(     weightedMeanScores(x = v3, i = i3), rep(3    ,2))
  expect_equal(           medianScores(x = v3, i = i3), rep(2    ,2))
  expect_equal(             modeScores(x = v3, i = i3), rep(1    ,2))
  expect_equal(         midrangeScores(x = v3, i = i3), rep(3.5  ,2))
  expect_equal(         midhingeScores(x = v3, i = i3), rep(2.75 ,2))
  expect_equal(          trimeanScores(x = v3, i = i3), rep(2.375,2))
  expect_equal(          briskowScores(x = v3, i = i3), rep(0    ,2))
  expect_equal(  reviewedBriskowScores(x = v3, i = i3), rep(0    ,2))
  expect_equal(      weightedSumScores(x = v3, i = i3), rep(9    ,2))
  expect_equal(interquartileMeanScores(x = v3, i = i3), rep(getDefaultNaValue(),2))
  expect_equal(           ssGseaScores(x = v3, i = i3), rep(getDefaultNaValue(),2))
  expect_equal(             gsvaScores(x = v3, i = i3), rep(getDefaultNaValue(),2))
  expect_equal(            plageScores(x = v3, i = i3), rep(getDefaultNaValue(),2))
  expect_equal(                zScores(x = v3, i = i3), rep(getDefaultNaValue(),2))
})

## Test 4-by-1 matrices ----------------------------------------------

test_that("Summary Scores functions works with 4-by-2 matrix and signature with 4 matching elements", {
  expect_equal(             meanScores(x = v4, i = i4), rep(3                  ,2))
  expect_equal(      trimmedMeanScores(x = v4, i = i4), rep(3                  ,2))
  expect_equal(     weightedMeanScores(x = v4, i = i4), rep(3                  ,2))
  expect_equal(           medianScores(x = v4, i = i4), rep(3                  ,2))
  expect_equal(             modeScores(x = v4, i = i4), rep(3                  ,2))
  expect_equal(         midrangeScores(x = v4, i = i4), rep(3                  ,2))
  expect_equal(         midhingeScores(x = v4, i = i4), rep(3                  ,2))
  expect_equal(          trimeanScores(x = v4, i = i4), rep(3                  ,2))
  expect_equal(          briskowScores(x = v4, i = i4), rep(0                  ,2))
  expect_equal(  reviewedBriskowScores(x = v4, i = i4), rep(0                  ,2))
  expect_equal(interquartileMeanScores(x = v4, i = i4), rep(3                  ,2))
  expect_equal(      weightedSumScores(x = v4, i = i4), rep(12                 ,2))
  expect_equal(           ssGseaScores(x = v4, i = i4), rep(getDefaultNaValue(),2))
  expect_equal(             gsvaScores(x = v4, i = i4), rep(getDefaultNaValue(),2))
  expect_equal(            plageScores(x = v4, i = i4), rep(getDefaultNaValue(),2))
  expect_equal(                zScores(x = v4, i = i4), rep(getDefaultNaValue(),2))
})

## Test 5-by-1 matrices ----------------------------------------------

test_that("Summary Scores functions works with 5-by-2 matrix and signature with 5 matching elements", {
  expect_equal(             meanScores(x = v5, i = i5), rep(4                  ,2))
  expect_equal(      trimmedMeanScores(x = v5, i = i5), rep(4                  ,2))
  expect_equal(     weightedMeanScores(x = v5, i = i5), rep(4                  ,2))
  expect_equal(           medianScores(x = v5, i = i5), rep(4                  ,2))
  expect_equal(             modeScores(x = v5, i = i5), rep(4                  ,2))
  expect_equal(         midrangeScores(x = v5, i = i5), rep(5                  ,2))
  expect_equal(         midhingeScores(x = v5, i = i5), rep(3                  ,2))
  expect_equal(          trimeanScores(x = v5, i = i5), rep(3.5                ,2))
  expect_equal(          briskowScores(x = v5, i = i5), rep(-1                 ,2))
  expect_equal(  reviewedBriskowScores(x = v5, i = i5), rep(-0.2               ,2))
  expect_equal(interquartileMeanScores(x = v5, i = i5), rep(3.4                ,2))
  expect_equal(      weightedSumScores(x = v5, i = i5), rep(20                 ,2))
  expect_equal(           ssGseaScores(x = v5, i = i5), rep(getDefaultNaValue(),2))
  expect_equal(             gsvaScores(x = v5, i = i5), rep(getDefaultNaValue(),2))
  expect_equal(            plageScores(x = v5, i = i5), rep(getDefaultNaValue(),2))
  expect_equal(                zScores(x = v5, i = i5), rep(getDefaultNaValue(),2))
})


## Test 6-by-1 matrices ----------------------------------------------

test_that("Summary Scores functions works with 6-by-2 matrix of equal elements and signature with 6 matching elements", {
  expect_equal(             meanScores(x = v6, i = i6), rep(8                  ,2))
  expect_equal(      trimmedMeanScores(x = v6, i = i6), rep(8                  ,2))
  expect_equal(     weightedMeanScores(x = v6, i = i6), rep(8                  ,2))
  expect_equal(           medianScores(x = v6, i = i6), rep(8                  ,2))
  expect_equal(             modeScores(x = v6, i = i6), rep(8                  ,2))
  expect_equal(         midrangeScores(x = v6, i = i6), rep(8                  ,2))
  expect_equal(         midhingeScores(x = v6, i = i6), rep(8                  ,2))
  expect_equal(          trimeanScores(x = v6, i = i6), rep(8                  ,2))
  expect_equal(          briskowScores(x = v6, i = i6), rep(0                  ,2))
  expect_equal(  reviewedBriskowScores(x = v6, i = i6), rep(0                  ,2))
  expect_equal(interquartileMeanScores(x = v6, i = i6), rep(8                  ,2))
  expect_equal(      weightedSumScores(x = v6, i = i6), rep(48                 ,2))
  expect_equal(           ssGseaScores(x = v6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(             gsvaScores(x = v6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(            plageScores(x = v6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(                zScores(x = v6, i = i6), rep(getDefaultNaValue(),2))
})

## Test matrices of zeros ----------------------------------------------

test_that("Summary Scores functions works with 2-by-2 matrix of zeros and signature with 2 matching elements", {
  expect_equal(             meanScores(x = z2, i = i2), rep(0                  ,2))
  expect_equal(      trimmedMeanScores(x = z2, i = i2), rep(0                  ,2))
  expect_equal(     weightedMeanScores(x = z2, i = i2), rep(0                  ,2))
  expect_equal(           medianScores(x = z2, i = i2), rep(0                  ,2))
  expect_equal(             modeScores(x = z2, i = i2), rep(0                  ,2))
  expect_equal(         midrangeScores(x = z2, i = i2), rep(0                  ,2))
  expect_equal(         midhingeScores(x = z2, i = i2), rep(0                  ,2))
  expect_equal(          trimeanScores(x = z2, i = i2), rep(0                  ,2))
  expect_equal(          briskowScores(x = z2, i = i2), rep(0                  ,2))
  expect_equal(  reviewedBriskowScores(x = z2, i = i2), rep(0                  ,2))
  expect_equal(      weightedSumScores(x = z2, i = i2), rep(0                  ,2))
  expect_equal(interquartileMeanScores(x = z2, i = i2), rep(getDefaultNaValue(),2))
  expect_equal(           ssGseaScores(x = z2, i = i2), rep(getDefaultNaValue(),2))
  expect_equal(             gsvaScores(x = z2, i = i2), rep(getDefaultNaValue(),2))
  expect_equal(            plageScores(x = z2, i = i2), rep(getDefaultNaValue(),2))
  expect_equal(                zScores(x = z2, i = i2), rep(getDefaultNaValue(),2))
})

test_that("Summary Scores functions works with 6-by-2 matrix of zeros and signature with 6 matching elements", {
  expect_equal(             meanScores(x = z6, i = i6), rep(0                  ,2))
  expect_equal(      trimmedMeanScores(x = z6, i = i6), rep(0                  ,2))
  expect_equal(     weightedMeanScores(x = z6, i = i6), rep(0                  ,2))
  expect_equal(           medianScores(x = z6, i = i6), rep(0                  ,2))
  expect_equal(             modeScores(x = z6, i = i6), rep(0                  ,2))
  expect_equal(         midrangeScores(x = z6, i = i6), rep(0                  ,2))
  expect_equal(         midhingeScores(x = z6, i = i6), rep(0                  ,2))
  expect_equal(          trimeanScores(x = z6, i = i6), rep(0                  ,2))
  expect_equal(          briskowScores(x = z6, i = i6), rep(0                  ,2))
  expect_equal(  reviewedBriskowScores(x = z6, i = i6), rep(0                  ,2))
  expect_equal(interquartileMeanScores(x = z6, i = i6), rep(0                  ,2))
  expect_equal(      weightedSumScores(x = z6, i = i6), rep(0                  ,2))
  expect_equal(           ssGseaScores(x = z6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(             gsvaScores(x = z6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(            plageScores(x = z6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(                zScores(x = z6, i = i6), rep(getDefaultNaValue(),2))
})

## Test matrices of NAs ----------------------------------------------

test_that("Summary Scores functions works with 6-by-2 matrix of NAs (`na.rm = TRUE`) and signature with 6 matching elements", {
  expect_equal(             meanScores(x = na6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(      trimmedMeanScores(x = na6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(     weightedMeanScores(x = na6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(           medianScores(x = na6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(             modeScores(x = na6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(         midrangeScores(x = na6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(         midhingeScores(x = na6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(          trimeanScores(x = na6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(          briskowScores(x = na6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(  reviewedBriskowScores(x = na6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(interquartileMeanScores(x = na6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(      weightedSumScores(x = na6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(           ssGseaScores(x = na6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(             gsvaScores(x = na6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(            plageScores(x = na6, i = i6), rep(getDefaultNaValue(),2))
  expect_equal(                zScores(x = na6, i = i6), rep(getDefaultNaValue(),2))

})

test_that("Summary Scores functions works with 6-by-2 matrix of NAs (`na.rm = FALSE`) and signature with 6 matching elements", {
  expect_equal(             meanScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(      trimmedMeanScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(     weightedMeanScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(           medianScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(             modeScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(         midrangeScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(         midhingeScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(          trimeanScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(          briskowScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(  reviewedBriskowScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(interquartileMeanScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(      weightedSumScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(           ssGseaScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(             gsvaScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(            plageScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(                zScores(x = na6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
})

## Test matrices with numbers and NAs ----------------------------------------------

test_that("Summary Scores functions works with 5-by-2 matrix containing 3 real numbers and 2 NAs (`na.rm = TRUE`) and signature with 5 matching elements", {
  expect_equal(             meanScores(x = m5, i = i5, na.rm = TRUE), rep(3                  ,2))
  expect_equal(      trimmedMeanScores(x = m5, i = i5, na.rm = TRUE), rep(3                  ,2))
  expect_equal(     weightedMeanScores(x = m5, i = i5, na.rm = TRUE), rep(3                  ,2))
  expect_equal(           medianScores(x = m5, i = i5, na.rm = TRUE), rep(2                  ,2))
  expect_equal(             modeScores(x = m5, i = i5, na.rm = TRUE), rep(1                  ,2))
  expect_equal(         midrangeScores(x = m5, i = i5, na.rm = TRUE), rep(3.5                ,2))
  expect_equal(         midhingeScores(x = m5, i = i5, na.rm = TRUE), rep(2.75               ,2))
  expect_equal(          trimeanScores(x = m5, i = i5, na.rm = TRUE), rep(2.375              ,2))
  expect_equal(          briskowScores(x = m5, i = i5, na.rm = TRUE), rep(0                  ,2))
  expect_equal(  reviewedBriskowScores(x = m5, i = i5, na.rm = TRUE), rep(0                  ,2))
  expect_equal(      weightedSumScores(x = m5, i = i5, na.rm = TRUE), rep(9                  ,2))
  expect_equal(interquartileMeanScores(x = m5, i = i5, na.rm = TRUE), rep(getDefaultNaValue(),2))
  expect_equal(           ssGseaScores(x = m5, i = i5, na.rm = TRUE), rep(getDefaultNaValue(),2))
  expect_equal(             gsvaScores(x = m5, i = i5, na.rm = TRUE), rep(getDefaultNaValue(),2))
  expect_equal(            plageScores(x = m5, i = i5, na.rm = TRUE), rep(getDefaultNaValue(),2))
  expect_equal(                zScores(x = m5, i = i5, na.rm = TRUE), rep(getDefaultNaValue(),2))
})

test_that("Summary Scores functions works with 5-by-2 matrix containing 3 real numbers and 2 NAs (`na.rm = FALSE`) and signature with 5 matching elements", {
  expect_equal(             meanScores(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(      trimmedMeanScores(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(     weightedMeanScores(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(           medianScores(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(             modeScores(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(         midrangeScores(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(         midhingeScores(x = m5, i = i5, na.rm = FALSE), rep(2.75               ,2))
  expect_equal(          trimeanScores(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(          briskowScores(x = m5, i = i5, na.rm = FALSE), rep(0                  ,2))
  expect_equal(  reviewedBriskowScores(x = m5, i = i5, na.rm = FALSE), rep(0                  ,2))
  expect_equal(interquartileMeanScores(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(      weightedSumScores(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(           ssGseaScores(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(             gsvaScores(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(            plageScores(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(                zScores(x = m5, i = i5, na.rm = FALSE), rep(getDefaultNaValue(),2))
})

test_that("Summary Scores functions works with 6-by-2 matrix containing 3 real numbers and 2 NAs (`na.rm = TRUE`) and signature with 6 matching elements", {
  expect_equal(             meanScores(x = m6, i = i6, na.rm = TRUE), c(2.6, 2.8 ))
  expect_equal(      trimmedMeanScores(x = m6, i = i6, na.rm = TRUE), c(2.6, 2.8 ))
  expect_equal(     weightedMeanScores(x = m6, i = i6, na.rm = TRUE), c(2.6, 2.8 ))
  expect_equal(           medianScores(x = m6, i = i6, na.rm = TRUE), c(2  ,   2 ))
  expect_equal(             modeScores(x = m6, i = i6, na.rm = TRUE), c(1  ,   1 ))
  expect_equal(         midrangeScores(x = m6, i = i6, na.rm = TRUE), c(3.5, 3.5 ))
  expect_equal(         midhingeScores(x = m6, i = i6, na.rm = TRUE), c(2.0, 2.5 ))
  expect_equal(          trimeanScores(x = m6, i = i6, na.rm = TRUE), c(2.0, 2.25))
  expect_equal(          briskowScores(x = m6, i = i6, na.rm = TRUE), rep(0    ,2))
  expect_equal(  reviewedBriskowScores(x = m6, i = i6, na.rm = TRUE), rep(0    ,2))
  expect_equal(      weightedSumScores(x = m6, i = i6, na.rm = TRUE), rep(12.5 ,2))
  expect_equal(interquartileMeanScores(x = m6, i = i6, na.rm = TRUE), c(2.0, 2.3))
  expect_equal(           ssGseaScores(x = m6, i = i6, na.rm = TRUE), rep(NaN,2))
  expect_equal(             gsvaScores(x = m6, i = i6, na.rm = TRUE), c(1,1))
  expect_equal(            plageScores(x = m6, i = i6, na.rm = TRUE), c(-0.70710678, 0.70710678))
  expect_equal(                zScores(x = m6, i = i6, na.rm = TRUE), rep(0,2))
})

test_that("Summary Scores functions works with 6-by-2 matrix containing 3 real numbers and 2 NAs (`na.rm = FALSE`) and signature with 6 matching elements", {
  expect_equal(             meanScores(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(      trimmedMeanScores(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(     weightedMeanScores(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(           medianScores(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(             modeScores(x = m6, i = i6, na.rm = FALSE), rep(1,2))
  expect_equal(         midrangeScores(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(         midhingeScores(x = m6, i = i6, na.rm = FALSE), c(2.0, 2.5))
  expect_equal(          trimeanScores(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(          briskowScores(x = m6, i = i6, na.rm = FALSE), rep(0                  ,2))
  expect_equal(  reviewedBriskowScores(x = m6, i = i6, na.rm = FALSE), rep(0                  ,2))
  expect_equal(interquartileMeanScores(x = m6, i = i6, na.rm = FALSE), c(2.0, 2.3))
  expect_equal(      weightedSumScores(x = m6, i = i6, na.rm = FALSE), rep(getDefaultNaValue(),2))
  expect_equal(           ssGseaScores(x = m6, i = i6, na.rm = FALSE), rep(NaN,2))
  expect_equal(             gsvaScores(x = m6, i = i6, na.rm = FALSE), c(1, 1))
  expect_equal(            plageScores(x = m6, i = i6, na.rm = FALSE), c(-0.70710678, 0.70710678))
  expect_equal(                zScores(x = m6, i = i6, na.rm = FALSE), c(0, 0))
})

