library(usethis)
library(testthat)

#vector of numbers
v1 = c(1)
v2 = c(1,4)
v3 = c(2,6,1)
v4 = c(3,5,1,3)
v5 = c(1,4,4,2,9)
v6 = c(8,8,8,8,8,8)
v7 = c(1,1,4,4,3,2,1)
v8 = c(1,1,4,4,3,2,1,7)

#zeros
z1 = 0
z2 = c(0,0)
z6 = c(0,0,0,0,0,0)

#NAs
na1 = NA
na2 = c(NA,NA)
na6 = c(NA,NA,NA,NA,NA,NA)

#numbers and NAs
m2 = c(2, NA)
m3 = c(2, NA, 4)
m4 = c(2, NA, 3, 4)
m5 = c(2, 6, NA, NA, 1)

test_that("Summary Score functions works with length 1 vector", {
  expect_equal(   computeVectorScore(score =          "sum", x = v1), 1)
  expect_equal(   computeVectorScore(score =  "weightedSum", x = v1), 1)
  expect_equal(   computeVectorScore(score =         "mean", x = v1), 1)
  expect_equal(   computeVectorScore(score =  "trimmedMean", x = v1), 1)
  expect_equal(   computeVectorScore(score = "weightedMean", x = v1), 1)
  expect_equal(   computeVectorScore(score =       "median", x = v1), 1)
  expect_equal(   computeVectorScore(score =         "mode", x = v1), 1)
  expect_equal(   computeVectorScore(score =     "midrange", x = v1), 1)
  expect_equal(   computeVectorScore(score =     "midhinge", x = v1), 1)
  expect_equal(   computeVectorScore(score =      "trimean", x = v1), 1)
  expect_equal(   computeVectorScore(score =          "iqr", x = v1), 0)
  expect_equal(   computeVectorScore(score =          "iqm", x = v1), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "mad", x = v1), 0)
  expect_equal(   computeVectorScore(score =          "aad", x = v1), 0)
  expect_equal(   computeVectorScore(score =       "ssgsea", x = v1), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "gsva", x = v1), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =        "plage", x = v1), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "zscore", x = v1), getDefaultNaValue())
})

test_that("Summary Score functions works with length 2 vector", {
  expect_equal(   computeVectorScore(score =          "sum", x = v2), 5)
  expect_equal(   computeVectorScore(score =  "weightedSum", x = v2), 5)
  expect_equal(   computeVectorScore(score =         "mean", x = v2), 2.5)
  expect_equal(   computeVectorScore(score =  "trimmedMean", x = v2), 2.5)
  expect_equal(   computeVectorScore(score = "weightedMean", x = v2), 2.5)
  expect_equal(   computeVectorScore(score =       "median", x = v2), 2.5)
  expect_equal(   computeVectorScore(score =         "mode", x = v2), 1)
  expect_equal(   computeVectorScore(score =     "midrange", x = v2), 2.5)
  expect_equal(   computeVectorScore(score =     "midhinge", x = v2), 2.5)
  expect_equal(   computeVectorScore(score =      "trimean", x = v2), 2.5)
  expect_equal(   computeVectorScore(score =          "iqr", x = v2), 1.5)
  expect_equal(   computeVectorScore(score =          "iqm", x = v2), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "mad", x = v2), 2.2239)
  expect_equal(   computeVectorScore(score =          "aad", x = v2), 1.5)
  expect_equal(   computeVectorScore(score =       "ssgsea", x = v2), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "gsva", x = v2), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =        "plage", x = v2), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "zscore", x = v2), getDefaultNaValue())
})

test_that("Summary Score functions works with length 3 vector", {
  expect_equal(   computeVectorScore(score =          "sum", x = v3), 9)
  expect_equal(   computeVectorScore(score =  "weightedSum", x = v3), 9)
  expect_equal(   computeVectorScore(score =         "mean", x = v3), 3)
  expect_equal(   computeVectorScore(score =  "trimmedMean", x = v3), 3)
  expect_equal(   computeVectorScore(score = "weightedMean", x = v3), 3)
  expect_equal(   computeVectorScore(score =       "median", x = v3), 2)
  expect_equal(   computeVectorScore(score =         "mode", x = v3), 1)
  expect_equal(   computeVectorScore(score =     "midrange", x = v3), 3.5)
  expect_equal(   computeVectorScore(score =     "midhinge", x = v3), 2.75)
  expect_equal(   computeVectorScore(score =      "trimean", x = v3), 2.375)
  expect_equal(   computeVectorScore(score =          "iqr", x = v3), 2.5)
  expect_equal(   computeVectorScore(score =          "iqm", x = v3), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "mad", x = v3), 1.4826)
  expect_equal(   computeVectorScore(score =          "aad", x = v3), 1.66666667)
  expect_equal(   computeVectorScore(score =       "ssgsea", x = v3), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "gsva", x = v3), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =        "plage", x = v3), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "zscore", x = v3), getDefaultNaValue())
})

test_that("Summary Score functions works with length 4 vector", {
  expect_equal(   computeVectorScore(score =          "sum", x = v4), 12)
  expect_equal(   computeVectorScore(score =  "weightedSum", x = v4), 12)
  expect_equal(   computeVectorScore(score =         "mean", x = v4), 3)
  expect_equal(   computeVectorScore(score =  "trimmedMean", x = v4), 3)
  expect_equal(   computeVectorScore(score = "weightedMean", x = v4), 3)
  expect_equal(   computeVectorScore(score =       "median", x = v4), 3)
  expect_equal(   computeVectorScore(score =         "mode", x = v4), 3)
  expect_equal(   computeVectorScore(score =     "midrange", x = v4), 3)
  expect_equal(   computeVectorScore(score =     "midhinge", x = v4), 3)
  expect_equal(   computeVectorScore(score =      "trimean", x = v4), 3)
  expect_equal(   computeVectorScore(score =          "iqr", x = v4), 1)
  expect_equal(   computeVectorScore(score =          "iqm", x = v4), 3)
  expect_equal(   computeVectorScore(score =          "mad", x = v4), 1.4826)
  expect_equal(   computeVectorScore(score =          "aad", x = v4), 1)
  expect_equal(   computeVectorScore(score =       "ssgsea", x = v4), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "gsva", x = v4), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =        "plage", x = v4), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "zscore", x = v4), getDefaultNaValue())
})

test_that("Summary Score functions works with length 5 vector", {
  expect_equal(   computeVectorScore(score =          "sum", x = v5), 20)
  expect_equal(   computeVectorScore(score =  "weightedSum", x = v5), 20)
  expect_equal(   computeVectorScore(score =         "mean", x = v5), 4)
  expect_equal(   computeVectorScore(score =  "trimmedMean", x = v5), 4)
  expect_equal(   computeVectorScore(score = "weightedMean", x = v5), 4)
  expect_equal(   computeVectorScore(score =       "median", x = v5), 4)
  expect_equal(   computeVectorScore(score =         "mode", x = v5), 4)
  expect_equal(   computeVectorScore(score =     "midrange", x = v5), 5)
  expect_equal(   computeVectorScore(score =     "midhinge", x = v5), 3)
  expect_equal(   computeVectorScore(score =      "trimean", x = v5), 3.5)
  expect_equal(   computeVectorScore(score =          "iqr", x = v5), 2)
  expect_equal(   computeVectorScore(score =          "iqm", x = v5), 3.4)
  expect_equal(   computeVectorScore(score =          "mad", x = v5), 2.9652)
  expect_equal(   computeVectorScore(score =          "aad", x = v5), 2)
  expect_equal(   computeVectorScore(score =       "ssgsea", x = v5), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "gsva", x = v5), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =        "plage", x = v5), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "zscore", x = v5), getDefaultNaValue())
})

test_that("Summary Score functions works with length 6 vector of equal elements", {
  expect_equal(   computeVectorScore(score =          "sum", x = v6), 48)
  expect_equal(   computeVectorScore(score =  "weightedSum", x = v6), 48)
  expect_equal(   computeVectorScore(score =         "mean", x = v6), 8)
  expect_equal(   computeVectorScore(score =  "trimmedMean", x = v6), 8)
  expect_equal(   computeVectorScore(score = "weightedMean", x = v6), 8)
  expect_equal(   computeVectorScore(score =       "median", x = v6), 8)
  expect_equal(   computeVectorScore(score =         "mode", x = v6), 8)
  expect_equal(   computeVectorScore(score =     "midrange", x = v6), 8)
  expect_equal(   computeVectorScore(score =     "midhinge", x = v6), 8)
  expect_equal(   computeVectorScore(score =      "trimean", x = v6), 8)
  expect_equal(   computeVectorScore(score =          "iqr", x = v6), 0)
  expect_equal(   computeVectorScore(score =          "iqm", x = v6), 8)
  expect_equal(   computeVectorScore(score =          "mad", x = v6), 0)
  expect_equal(   computeVectorScore(score =          "aad", x = v6), 0)
  expect_equal(   computeVectorScore(score =       "ssgsea", x = v6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "gsva", x = v6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =        "plage", x = v6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "zscore", x = v6), getDefaultNaValue())
})


test_that("Summary Score functions works with length 2 vector of zeros", {
  expect_equal(   computeVectorScore(score =          "sum", x = z2), 0)
  expect_equal(   computeVectorScore(score =  "weightedSum", x = z2), 0)
  expect_equal(   computeVectorScore(score =         "mean", x = z2), 0)
  expect_equal(   computeVectorScore(score =  "trimmedMean", x = z2), 0)
  expect_equal(   computeVectorScore(score = "weightedMean", x = z2), 0)
  expect_equal(   computeVectorScore(score =       "median", x = z2), 0)
  expect_equal(   computeVectorScore(score =         "mode", x = z2), 0)
  expect_equal(   computeVectorScore(score =     "midrange", x = z2), 0)
  expect_equal(   computeVectorScore(score =     "midhinge", x = z2), 0)
  expect_equal(   computeVectorScore(score =      "trimean", x = z2), 0)
  expect_equal(   computeVectorScore(score =          "iqr", x = z2), 0)
  expect_equal(   computeVectorScore(score =          "iqm", x = z2), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "mad", x = z2), 0)
  expect_equal(   computeVectorScore(score =          "aad", x = z2), 0)
  expect_equal(   computeVectorScore(score =       "ssgsea", x = z2), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "gsva", x = z2), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =        "plage", x = z2), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "zscore", x = z2), getDefaultNaValue())
})

test_that("Summary Score functions works with length 6 vector of zeros", {
  expect_equal(   computeVectorScore(score =          "sum", x = z6), 0)
  expect_equal(   computeVectorScore(score =  "weightedSum", x = z6), 0)
  expect_equal(   computeVectorScore(score =         "mean", x = z6), 0)
  expect_equal(   computeVectorScore(score =  "trimmedMean", x = z6), 0)
  expect_equal(   computeVectorScore(score = "weightedMean", x = z6), 0)
  expect_equal(   computeVectorScore(score =       "median", x = z6), 0)
  expect_equal(   computeVectorScore(score =         "mode", x = z6), 0)
  expect_equal(   computeVectorScore(score =     "midrange", x = z6), 0)
  expect_equal(   computeVectorScore(score =     "midhinge", x = z6), 0)
  expect_equal(   computeVectorScore(score =      "trimean", x = z6), 0)
  expect_equal(   computeVectorScore(score =          "iqr", x = z6), 0)
  expect_equal(   computeVectorScore(score =          "iqm", x = z6), 0)
  expect_equal(   computeVectorScore(score =          "mad", x = z6), 0)
  expect_equal(   computeVectorScore(score =          "aad", x = z6), 0)
  expect_equal(   computeVectorScore(score =       "ssgsea", x = z6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "gsva", x = z6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =        "plage", x = z6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "zscore", x = z6), getDefaultNaValue())
})


test_that("Summary Score functions works with length 6 vector of NAs (`na.rm = TRUE`)", {
  expect_equal(   computeVectorScore(score =          "sum", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =  "weightedSum", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "mean", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =  "trimmedMean", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score = "weightedMean", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "median", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "mode", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =     "midrange", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =     "midhinge", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =      "trimean", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "iqr", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "iqm", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "mad", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "aad", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "ssgsea", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "gsva", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =        "plage", x = na6), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "zscore", x = na6), getDefaultNaValue())
})

test_that("Summary Score functions works with length 6 vector of NAs (`na.rm = FALSE`)", {
  expect_equal(   computeVectorScore(score =          "sum", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =  "weightedSum", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "mean", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =  "trimmedMean", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score = "weightedMean", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "median", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "mode", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =     "midrange", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =     "midhinge", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =      "trimean", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "iqr", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "iqm", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "mad", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "aad", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "ssgsea", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "gsva", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =        "plage", x = na6, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "zscore", x = na6, na.rm = FALSE), getDefaultNaValue())
})


test_that("Summary Score functions works with length 5 vector of 3 real numbers and 2 NAs (`na.rm = TRUE`)", {
  expect_equal(   computeVectorScore(score =          "sum", x = m5, na.rm = TRUE), 9)
  expect_equal(   computeVectorScore(score =  "weightedSum", x = m5, na.rm = TRUE), 9)
  expect_equal(   computeVectorScore(score =         "mean", x = m5, na.rm = TRUE), 3)
  expect_equal(   computeVectorScore(score =  "trimmedMean", x = m5, na.rm = TRUE), 3)
  expect_equal(   computeVectorScore(score = "weightedMean", x = m5, na.rm = TRUE), 3)
  expect_equal(   computeVectorScore(score =       "median", x = m5, na.rm = TRUE), 2)
  expect_equal(   computeVectorScore(score =         "mode", x = m5, na.rm = TRUE), 1)
  expect_equal(   computeVectorScore(score =     "midrange", x = m5, na.rm = TRUE), 3.5)
  expect_equal(   computeVectorScore(score =     "midhinge", x = m5, na.rm = TRUE), 2.75)
  expect_equal(   computeVectorScore(score =      "trimean", x = m5, na.rm = TRUE), 2.375)
  expect_equal(   computeVectorScore(score =          "iqr", x = m5, na.rm = TRUE), 2.5)
  expect_equal(   computeVectorScore(score =          "iqm", x = m5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "mad", x = m5, na.rm = TRUE), 1.4826)
  expect_equal(   computeVectorScore(score =          "aad", x = m5, na.rm = TRUE), 1.66666667)
  expect_equal(   computeVectorScore(score =       "ssgsea", x = m5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "gsva", x = m5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =        "plage", x = m5, na.rm = TRUE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "zscore", x = m5, na.rm = TRUE), getDefaultNaValue())
})

test_that("Summary Score functions works with length 5 vector of 3 real numbers and 2 NAs (`na.rm = FALSE`)", {
  expect_equal(   computeVectorScore(score =          "sum", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =  "weightedSum", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "mean", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =  "trimmedMean", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score = "weightedMean", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "median", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "mode", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =     "midrange", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =     "midhinge", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =      "trimean", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "iqr", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "iqm", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "mad", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =          "aad", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "ssgsea", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =         "gsva", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =        "plage", x = m5, na.rm = FALSE), getDefaultNaValue())
  expect_equal(   computeVectorScore(score =       "zscore", x = m5, na.rm = FALSE), getDefaultNaValue())
})

